import React from 'react';
import { AlertTriangle, ArrowLeft, BookOpenCheck, ClipboardCheck, Database, ExternalLink, FileWarning, Scale, ShieldAlert, UserCheck } from 'lucide-react';
import { withBasePath } from '../lib/routes';
import PageNavigation, { pageNavigationAsideClassName } from './PageNavigation';

const factors = ['當學年度招生名額、校科與招生管道', '報名人數、考生成績分布與志願序', '各就學區的超額比序、同分比序及跨區規定', '身分資格、特殊身分、加分或優先入學條件', '簡章修訂、時程異動及招生單位的最新公告'];
const checklist = ['以成績通知單核對輸入的會考成績與標示。', '確認所屬就學區、報名資格及欲使用的招生管道。', '逐項查閱目標校科當年度的簡章、名額與比序規則。', '一併評估興趣、性向、通勤、學費及學校特色。', '有疑問時，向國中輔導老師、招生委員會或目標學校確認。'];
const panel = 'rounded-2xl border-4 border-slate-900 bg-white p-5 shadow-[5px_5px_0_#0f172a] sm:p-7';

export default function DisclaimerPage() {
  return <main className="disclaimer-page min-h-screen overflow-x-clip bg-slate-50 text-slate-900">
    <section className="border-b-4 border-slate-900 bg-slate-900 text-white"><div className="mx-auto max-w-6xl px-4 py-5 sm:px-6 lg:px-8">
      <a href={withBasePath('/')} className="inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-3 py-2 text-sm font-black text-slate-900 shadow-[2px_2px_0_#fbbf24] transition hover:-translate-y-0.5 sm:px-4"><ArrowLeft className="h-4 w-4" />返回首頁</a>
      <div className="grid gap-8 py-10 lg:grid-cols-[1fr_310px] lg:items-end"><div><div className="mb-5 inline-flex items-center gap-3 rounded-2xl border-2 border-white/30 bg-white/10 px-4 py-3"><div className="rounded-xl border-2 border-slate-900 bg-amber-300 p-2 text-slate-900"><Scale className="h-6 w-6" /></div><div><p className="text-xs font-black tracking-widest text-amber-200">IMPORTANT NOTICE</p><p className="text-sm font-black text-slate-200">最後更新：2026 年 8 月 26 日</p></div></div><h1 className="text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">免責聲明</h1><p className="mt-5 max-w-3xl text-base font-bold leading-8 text-slate-200 sm:text-lg">本網站是民間開發的升學資訊與規劃工具，協助整理會考成績、校科資料與志願選項；不是政府機關、招生委員會、學校或正式報名、分發系統。</p></div><div className="rounded-2xl border-4 border-amber-300 bg-amber-100 p-5 text-slate-900 shadow-[5px_5px_0_rgba(255,255,255,0.22)]"><p className="text-sm font-black text-amber-800">最重要的原則</p><p className="mt-2 text-xl font-black leading-8">資格、名額、比序、時程與錄取結果，一律以當學年度官方簡章及公告為準。</p></div></div>
    </div></section>
    <section className="mx-auto grid max-w-6xl gap-6 px-4 py-8 sm:px-6 sm:py-10 lg:grid-cols-[240px_1fr] lg:px-8"><aside className={pageNavigationAsideClassName}><PageNavigation navClassName="rounded-2xl border-4 border-slate-900 bg-white p-4 shadow-[4px_4px_0_#0f172a]" items={[{ id: 'scope', label: '服務定位' }, { id: 'limits', label: '分析與資料限制' }, { id: 'decision', label: '選填前請確認' }, { id: 'privacy', label: '資料與第三方服務' }, { id: 'official', label: '官方資訊優先' }]} /></aside><div className="min-w-0 space-y-6">
      <section id="scope" className={panel}><div className="flex items-start gap-4"><div className="rounded-xl border-2 border-slate-900 bg-sky-100 p-3"><BookOpenCheck className="h-7 w-7 text-sky-700" /></div><div><h2 className="text-2xl font-black sm:text-3xl">一、服務定位與範圍</h2><p className="mt-4 text-sm font-bold leading-8 text-slate-700 sm:text-base">本站依使用者輸入的成績、就學區與偏好，提供會考積分換算、校科搜尋與比較、落點參考、志願規劃、結果匯出與分享等功能；亦提供 LINE 會員登入與免廣告服務。本站不代為報名、不驗證考生資格、不審核證明文件、不代填正式志願，也不執行錄取或分發。</p><p className="mt-3 text-sm font-bold leading-8 text-slate-700 sm:text-base">所有結果僅用於協助整理資訊及與家長、輔導老師討論，不取代招生單位、學校輔導人員或其他專業意見。</p></div></div></section>
      <section id="limits" className="scroll-mt-8"><div className="mb-4"><h2 className="text-2xl font-black sm:text-3xl">二、分析結果與資料限制</h2><p className="mt-2 text-sm font-bold leading-7 text-slate-600">結果是依輸入條件與本站當下資料產生的參考，不是錄取預測或保證。</p></div><div className="grid gap-4"><article className={panel}><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border-2 border-slate-900 bg-rose-100"><ShieldAlert className="h-6 w-6 text-rose-700" /></div><div><h3 className="text-xl font-black">不保證錄取或資格</h3><p className="mt-2 text-sm font-bold leading-7 text-slate-700">推薦清單、歷年成績、分數區間、排序、落點標示與分析文字，不構成錄取保證、招生資格認定、報名資格確認或任何招生結果承諾。</p></div></div></article><article className={panel}><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border-2 border-slate-900 bg-amber-100"><AlertTriangle className="h-6 w-6 text-amber-700" /></div><div><h3 className="text-xl font-black">實際結果會受多項因素影響</h3><ul className="mt-3 grid gap-2 sm:grid-cols-2">{factors.map((factor) => <li key={factor} className="flex gap-2 text-sm font-bold leading-6 text-slate-700"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-amber-500" />{factor}</li>)}</ul></div></div></article><article className={panel}><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border-2 border-slate-900 bg-indigo-100"><FileWarning className="h-6 w-6 text-indigo-700" /></div><div><h3 className="text-xl font-black">資料與功能可能調整</h3><p className="mt-2 text-sm font-bold leading-7 text-slate-700">本站資料、功能與外部連結可能因更新、修正、維護或第三方服務狀態而變動或暫時無法使用。若本站內容與官方公告不同，請以官方公告為準；發現疑似錯誤時，請使用本站的問題回報功能告知我們。</p></div></div></article></div></section>
      <section id="decision" className="scroll-mt-8 rounded-2xl border-4 border-slate-900 bg-sky-100 p-5 shadow-[5px_5px_0_#0f172a] sm:p-7"><div className="flex items-center gap-3"><ClipboardCheck className="h-8 w-8 text-sky-800" /><h2 className="text-2xl font-black sm:text-3xl">三、志願選填前請自行確認</h2></div><p className="mt-3 text-sm font-bold leading-7 text-slate-700">選校與填志願的最終決定由使用者自行作成。送出正式志願前，建議至少完成以下核對：</p><ol className="mt-5 grid gap-3 sm:grid-cols-2">{checklist.map((item, index) => <li key={item} className="flex gap-3 rounded-xl border-2 border-slate-900 bg-white p-4 text-sm font-bold leading-7"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border-2 border-slate-900 bg-amber-300 font-black">{index + 1}</span>{item}</li>)}</ol></section>
      <section id="privacy" className={panel}><div className="flex items-center gap-3"><Database className="h-7 w-7 text-emerald-700" /><h2 className="text-2xl font-black sm:text-3xl">四、資料、裝置與第三方服務</h2></div><div className="mt-4 grid gap-4 md:grid-cols-2"><p className="text-sm font-bold leading-8 text-slate-700">請只輸入分析所需資料，例如成績、就學區與偏好；不要輸入姓名、身分證字號、准考證號、住址、電話或其他非必要個人資料。分析結果與部分偏好會使用瀏覽器儲存技術，清除瀏覽資料或更換裝置後，暫存內容可能消失。</p><p className="text-sm font-bold leading-8 text-slate-700">如使用 LINE 登入、綠界付款、Google 服務或外部連結，相關資料處理及服務可用性亦受該服務提供者的規範影響。會員、付款、Cookie 與資料處理的詳細說明，請以隱私權政策及服務條款為準。</p></div><div className="mt-5 flex gap-3 sm:justify-end"><a href={withBasePath('/privacy')} className="inline-flex min-w-0 flex-1 items-center justify-center gap-2 rounded-xl border-2 border-slate-900 bg-emerald-100 px-3 py-3 text-sm font-black shadow-[2px_2px_0_#0f172a] sm:flex-none sm:px-4">隱私權政策 <ExternalLink className="h-4 w-4 shrink-0" /></a><a href={withBasePath('/terms')} className="inline-flex min-w-0 flex-1 items-center justify-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-3 py-3 text-sm font-black shadow-[2px_2px_0_#0f172a] sm:flex-none sm:px-4">服務條款 <ExternalLink className="h-4 w-4 shrink-0" /></a></div></section>
      <section id="official" className="scroll-mt-8 rounded-2xl border-4 border-slate-900 bg-amber-300 p-5 shadow-[5px_5px_0_#0f172a] sm:p-7"><div className="flex items-center gap-3"><UserCheck className="h-7 w-7 text-amber-900" /><h2 className="text-2xl font-black sm:text-3xl">五、官方資訊優先</h2></div><p className="mt-4 text-sm font-bold leading-8 text-slate-800">高中職及五專的招生簡章、實際名額、日程與作業規則，會依學年度、招生區、學制與招生管道而不同。請在填志願或報名前，至所屬招生區與目標學校的官方網站逐項核對。</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><a href="https://www.moe.gov.tw/News_Content.aspx?n=9E7AC85F1954DDA8&s=257B0F248023A5A5&sms=169B8E91BB75571F" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border-2 border-slate-900 bg-white p-4 text-sm font-black shadow-[2px_2px_0_#0f172a]">教育部：115 學年度免試入學資訊 <ExternalLink className="h-4 w-4" /></a><a href="https://www.techadmi.edu.tw/bbs-detail.php?gid=480&nid=1139" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border-2 border-slate-900 bg-white p-4 text-sm font-black shadow-[2px_2px_0_#0f172a]">招策會：115 學年度五專簡章 <ExternalLink className="h-4 w-4" /></a></div><p className="mt-5 text-sm font-bold leading-7 text-slate-800">本頁為使用提醒與資訊導覽，不構成法律、教育、升學、財務或其他專業意見。若不同意本頁、隱私權政策或服務條款所述原則，請停止使用本站服務。</p></section>
    </div></section>
  </main>;
}
