import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, ChevronDown, ChevronUp, Flame, Megaphone, Search, X } from 'lucide-react';
import { withBasePath } from '../lib/routes';
import { newsArticles } from '../lib/news';

export default function LatestNewsPage() {
  const [query, setQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('全部');
  const [showCategories, setShowCategories] = useState(false);
  const categories = useMemo(() => ['全部', ...Array.from(new Set(newsArticles.map((article) => article.category)))], []);
  const visibleCategories = showCategories ? categories : [];
  const orderedArticles = useMemo(() => [...newsArticles].sort((left, right) => right.publishedAt.localeCompare(left.publishedAt) || Number(right.id) - Number(left.id)), []);
  const visibleArticles = useMemo(() => {
    const keyword = query.trim().toLocaleLowerCase();
    return orderedArticles.filter((article) => {
      const matchesCategory = selectedCategory === '全部' || article.category === selectedCategory;
      const matchesQuery = !keyword || [article.title, article.summary, article.category].some((value) => value.toLocaleLowerCase().includes(keyword));
      return matchesCategory && matchesQuery;
    });
  }, [orderedArticles, query, selectedCategory]);
  const hasFilters = query.trim().length > 0 || selectedCategory !== '全部';
  const clearFilters = () => { setQuery(''); setSelectedCategory('全部'); };

  return <main className="min-h-screen bg-[#f8fafc] text-slate-900">
    <section className="overflow-hidden border-b-4 border-slate-900 bg-gradient-to-br from-amber-200 via-orange-100 to-white"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 sm:py-10"><a href={withBasePath('/')} className="inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-4 py-2 text-sm font-black shadow-[3px_3px_0_#0f172a]"><ArrowLeft className="h-4 w-4" />返回首頁</a><div className="mt-10 max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border-2 border-slate-900 bg-slate-900 px-4 py-2 text-xs font-black tracking-[.16em] text-white"><Megaphone className="h-4 w-4 text-amber-300" />LATEST NEWS・最新消息</div><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">掌握網站最新動態</h1><p className="mt-5 text-base font-bold leading-8 text-slate-700 sm:text-lg">從志願選填提醒、會考準備到網站功能更新，讓你在關鍵時刻少一點慌張、多一點把握。</p></div></div></section>
    <section className="mx-auto max-w-5xl px-4 pt-8 sm:px-6 sm:pt-12"><div className="rounded-3xl border-2 border-slate-900 bg-white p-4 shadow-[3px_3px_0_#0f172a] sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><label className="relative block min-w-0 flex-1"><span className="sr-only">搜尋消息</span><Search className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋標題、摘要或分類" className="w-full rounded-xl border-2 border-slate-300 bg-slate-50 py-3 pl-11 pr-10 text-sm font-bold text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-indigo-600 focus:bg-white focus:ring-4 focus:ring-indigo-100" />{query && <button type="button" onClick={() => setQuery('')} aria-label="清除搜尋" className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1 text-slate-400 transition hover:bg-slate-200 hover:text-slate-900"><X className="h-4 w-4" /></button>}</label><p className="shrink-0 text-sm font-black text-slate-600">找到 <span className="text-indigo-700">{visibleArticles.length}</span> 則消息</p></div>{showCategories && <div className="mt-4 flex flex-wrap gap-2">{visibleCategories.map((category) => <button key={category} type="button" onClick={() => setSelectedCategory(category)} className={`rounded-full border-2 px-3 py-2 text-xs font-black transition ${selectedCategory === category ? 'border-slate-900 bg-indigo-600 text-white' : 'border-slate-200 bg-white text-slate-600 hover:border-slate-900 hover:bg-slate-50'}`}>{category}</button>)}</div>}<div className="mt-3 flex justify-end border-t-2 border-dashed border-slate-200 pt-3"><button type="button" onClick={() => setShowCategories((visible) => !visible)} className="inline-flex items-center gap-1.5 text-xs font-black text-indigo-700 transition hover:text-indigo-950 hover:underline hover:underline-offset-4">{showCategories ? '收起分類篩選' : `開啟分類篩選（${categories.length}）`}{showCategories ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</button></div></div></section>
    <section className="mx-auto max-w-5xl space-y-8 px-4 py-10 sm:px-6 sm:py-14">{visibleArticles.length > 0 ? visibleArticles.map((article, index) => <article key={article.id} className="relative overflow-hidden rounded-[2rem] border-4 border-slate-900 bg-white p-6 shadow-[3px_3px_0_#0f172a] sm:p-10"><div aria-hidden="true" className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-amber-200 blur-2xl" /><div className="relative"><div className="flex flex-wrap items-center gap-3">{index === 0 && !hasFilters && <span className="inline-flex items-center gap-1.5 rounded-full border-2 border-slate-900 bg-rose-500 px-3 py-1.5 text-xs font-black text-white"><Flame className="h-4 w-4 fill-amber-300 text-amber-300" />最新公告</span>}<span className="inline-flex items-center gap-1.5 rounded-full border-2 border-amber-300 bg-amber-50 px-3 py-1.5 text-xs font-black text-amber-900"><CalendarDays className="h-4 w-4" />{article.category}</span></div><time dateTime={article.publishedAt} className="mt-5 block text-sm font-black text-slate-500">發布日期：{article.publishedLabel}</time><h2 className="mt-3 text-3xl font-black leading-tight sm:text-4xl">{article.title}</h2><p className="mt-6 max-w-3xl text-base font-bold leading-8 text-slate-700 sm:text-lg">{article.summary}</p><div className="mt-6 flex justify-end"><a href={withBasePath(`/news/${article.id}`)} className="inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-4 py-2.5 text-sm font-black shadow-[2px_2px_0_#0f172a] transition hover:-translate-y-0.5 hover:bg-amber-50">閱讀完整內容<ArrowRight className="h-4 w-4" /></a></div></div></article>) : <div className="rounded-[2rem] border-4 border-dashed border-slate-300 bg-white p-10 text-center sm:p-14"><Search className="mx-auto h-10 w-10 text-slate-400" /><h2 className="mt-4 text-2xl font-black">找不到相符的消息</h2><p className="mt-2 text-sm font-bold leading-7 text-slate-600">試試不同關鍵字，或清除分類篩選後再查看。</p><button type="button" onClick={clearFilters} className="mt-6 rounded-xl border-2 border-slate-900 bg-amber-300 px-4 py-2.5 text-sm font-black shadow-[2px_2px_0_#0f172a] transition hover:bg-amber-400">清除篩選</button></div>}</section>
  </main>;
}
