import { ArrowLeft, ArrowRight, CalendarDays, Flame, Megaphone } from 'lucide-react';
import { withBasePath } from '../lib/routes';
import { newsArticles } from '../lib/news';

export default function LatestNewsPage() {
  const orderedArticles = [...newsArticles].sort((left, right) => right.publishedAt.localeCompare(left.publishedAt) || Number(right.id) - Number(left.id));
  return <main className="min-h-screen bg-[#f8fafc] text-slate-900">
    <section className="overflow-hidden border-b-4 border-slate-900 bg-gradient-to-br from-amber-200 via-orange-100 to-white"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 sm:py-10"><a href={withBasePath('/')} className="inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-4 py-2 text-sm font-black shadow-[3px_3px_0_#0f172a]"><ArrowLeft className="h-4 w-4" />返回首頁</a><div className="mt-10 max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border-2 border-slate-900 bg-slate-900 px-4 py-2 text-xs font-black tracking-[.16em] text-white"><Megaphone className="h-4 w-4 text-amber-300" />LATEST NEWS・最新消息</div><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">掌握網站最新動態</h1><p className="mt-5 text-base font-bold leading-8 text-slate-700 sm:text-lg">資料更新、服務公告與合作資訊都會整理在這裡。</p></div></div></section>
    <section className="mx-auto max-w-5xl space-y-8 px-4 py-10 sm:px-6 sm:py-14">{orderedArticles.map((article, index) => <article key={article.id} className="relative overflow-hidden rounded-[2rem] border-4 border-slate-900 bg-white p-6 shadow-[6px_6px_0_#0f172a] sm:p-10"><div aria-hidden="true" className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-amber-200 blur-2xl" /><div className="relative"><div className="flex flex-wrap items-center gap-3">{index === 0 && <span className="inline-flex items-center gap-1.5 rounded-full border-2 border-slate-900 bg-rose-500 px-3 py-1.5 text-xs font-black text-white"><Flame className="h-4 w-4 fill-amber-300 text-amber-300" />最新公告</span>}<span className="inline-flex items-center gap-1.5 rounded-full border-2 border-amber-300 bg-amber-50 px-3 py-1.5 text-xs font-black text-amber-900"><CalendarDays className="h-4 w-4" />{article.category}</span></div><time dateTime={article.publishedAt} className="mt-5 block text-sm font-black text-slate-500">發布日期：{article.publishedLabel}</time><h2 className="mt-3 text-3xl font-black leading-tight sm:text-4xl">{article.title}</h2><p className="mt-6 max-w-3xl text-base font-bold leading-8 text-slate-700 sm:text-lg">{article.summary}</p><div className="mt-6 flex justify-end"><a href={withBasePath(`/news/${article.id}`)} className="inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-4 py-2.5 text-sm font-black shadow-[2px_2px_0_#0f172a] transition hover:-translate-y-0.5 hover:bg-amber-50">閱讀完整內容<ArrowRight className="h-4 w-4" /></a></div></div></article>)}</section>
  </main>;
}
