import { ArrowLeft, CalendarDays, Megaphone } from 'lucide-react';
import { withBasePath } from '../lib/routes';
import { getNewsArticle } from '../lib/news';

export default function NewsArticlePage({ articleId }: { articleId: string }) {
  const article = getNewsArticle(articleId);
  if (!article) return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-3xl rounded-3xl border-4 border-slate-900 bg-white p-8 shadow-[5px_5px_0_#0f172a]"><h1 className="text-3xl font-black">找不到這篇文章</h1><a className="mt-6 inline-flex rounded-xl border-2 border-slate-900 px-4 py-2 font-black" href={withBasePath('/news')}>返回最新消息</a></div></main>;
  return <main className="min-h-screen bg-[#f8fafc] text-slate-900"><article><header className="border-b-4 border-slate-900 bg-gradient-to-br from-amber-100 via-white to-sky-100"><div className="mx-auto max-w-4xl px-4 py-6 sm:px-6 sm:py-10"><a href={withBasePath('/news')} className="inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-4 py-2 text-sm font-black shadow-[2px_2px_0_#0f172a]"><ArrowLeft className="h-4 w-4" />返回最新消息</a><div className="mt-10"><div className="flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-2 rounded-full bg-slate-900 px-3 py-1.5 text-xs font-black text-white"><Megaphone className="h-4 w-4 text-amber-300" />{article.category}</span><span className="inline-flex items-center gap-1.5 text-sm font-black text-slate-600"><CalendarDays className="h-4 w-4" /><time dateTime={article.publishedAt}>{article.publishedLabel}</time></span></div><h1 className="mt-7 text-4xl font-black leading-tight tracking-tight sm:text-6xl">{article.title}</h1><p className="mt-6 max-w-3xl text-lg font-bold leading-9 text-slate-700 sm:text-xl">{article.summary}</p></div></div></header><div className="mx-auto max-w-3xl px-4 py-10 sm:px-6 sm:py-14">{article.body.map((section) => <section key={section.heading} className="mb-10"><h2 className="border-l-8 border-amber-400 pl-4 text-2xl font-black sm:text-3xl">{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-5 text-base font-bold leading-9 text-slate-700 sm:text-lg">{paragraph}</p>)}</section>)}<aside className="rounded-3xl border-2 border-slate-900 bg-amber-50 p-5"><p className="text-sm font-black text-amber-900">資料與提醒</p><p className="mt-2 text-sm font-bold leading-7 text-slate-700">{article.sourceNote}</p></aside></div></article></main>;
}
