import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, BadgeCheck, BookOpenCheck, Crown, Lightbulb, Loader2, LockKeyhole, RotateCcw, TrendingUp } from 'lucide-react';
import { callBackend } from '../lib/api';
import { getMembershipStatus } from '../lib/membership';
import { withBasePath } from '../lib/routes';

const RESULTS_STORAGE_KEY = 'tw-admission-analysis-results';
const subjects = [
  { id: 'chinese', label: '國文' }, { id: 'english', label: '英文' }, { id: 'math', label: '數學' },
  { id: 'science', label: '自然' }, { id: 'social', label: '社會' }, { id: 'composition', label: '作文' },
] as const;
type Subject = typeof subjects[number]['id'];
type SchoolChange = { name: string; district?: string | null; type?: string | null; group?: string | null; zone: string };
type ZoneChange = SchoolChange & { fromZone: string; toZone: string };
type ChangeResult = { label: string; before: { totalPoints: number; totalCredits: number | null; count: number }; after: { totalPoints: number; totalCredits: number | null; count: number }; added: SchoolChange[]; removed: SchoolChange[]; zoneChanges: ZoneChange[] };
type HistoryItem = ChangeResult & { id: string };
const zoneText: Record<string, string> = { reach: '夢幻區', target: '實際區', safe: '保守區' };

function readStoredResult() {
  try { const raw = sessionStorage.getItem(RESULTS_STORAGE_KEY); return raw ? JSON.parse(raw) : null; } catch { return null; }
}

export default function ScoreChangePage() {
  const stored = useMemo(readStoredResult, []);
  const [member, setMember] = useState<boolean | null>(null);
  const [result, setResult] = useState<ChangeResult | null>(null);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [loading, setLoading] = useState('');
  const [error, setError] = useState('');
  const resultRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let current = true;
    getMembershipStatus().then((status) => current && setMember(status.active)).catch(() => current && setMember(false));
    return () => { current = false; };
  }, []);

  useEffect(() => {
    if (result) resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }, [result]);

  if (!stored?.results || !stored?.scores) return <EmptyState />;
  const scores = stored.scores as Record<string, unknown>;
  const vocationalGroups = Array.isArray(stored.vocationalGroups) ? stored.vocationalGroups : [];
  const isScenarioLocked = Boolean(result);

  const runScenario = async (subject: Subject, direction: 'increase' | 'decrease') => {
    const requestKey = `${subject}-${direction}`;
    setLoading(requestKey); setError('');
    try {
      const response = await callBackend<ChangeResult>({
        action: 'analyzeScoreChange', subject, direction, region: String(scores.region || ''),
        scores: { chinese: scores.chinese, english: scores.english, math: scores.math, science: scores.science, social: scores.social, composition: Number(scores.composition) },
        filters: { schoolOwnership: scores.schoolOwnership, schoolType: scores.schoolType, vocationalGroups },
      });
      setResult(response);
      setHistory((items) => [{ ...response, id: `${subject}-${direction}-${Date.now()}` }, ...items.filter((item) => item.label !== response.label)].slice(0, 6));
    } catch (cause) { setError(cause instanceof Error ? cause.message : '暫時無法完成一分改變分析。'); } finally { setLoading(''); }
  };

  return <main className="min-h-screen bg-[#f5f6fb] px-4 py-6 text-slate-900 sm:px-6 sm:py-10"><div className="mx-auto max-w-6xl">
    <div className="flex items-center justify-between gap-3"><a href={withBasePath('/results')} className="inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-4 py-2.5 text-sm font-black text-slate-700 shadow-[3px_3px_0_#0f172a] transition hover:-translate-y-0.5 hover:bg-slate-50 hover:text-slate-950 hover:shadow-[5px_5px_0_#0f172a] active:translate-y-0 active:shadow-none"><ArrowLeft className="h-4 w-4" />回到分析結果</a><span className="inline-flex shrink-0 items-center gap-2 rounded-full border border-indigo-200 bg-white px-3 py-2 text-xs font-bold tracking-wide text-indigo-800"><Crown className="h-4 w-4 fill-amber-300 text-amber-600" />會員專屬分析</span></div>
    <header className="relative mt-5 overflow-hidden rounded-[2rem] border-2 border-slate-900 bg-[radial-gradient(circle_at_88%_12%,rgba(196,181,253,.52),transparent_27%),linear-gradient(135deg,#ffffff_0%,#f3f0ff_55%,#eef5ff_100%)] px-6 py-9 shadow-[6px_6px_0_#0f172a] sm:px-10 sm:py-12"><div aria-hidden="true" className="absolute inset-0 opacity-[.35] [background-image:linear-gradient(rgba(99,102,241,.10)_1px,transparent_1px),linear-gradient(90deg,rgba(99,102,241,.10)_1px,transparent_1px)] [background-size:28px_28px]" /><div aria-hidden="true" className="absolute -right-16 -top-20 h-64 w-64 rounded-full border border-indigo-200/70" /><div className="relative"><div className="max-w-3xl"><p className="flex items-center gap-2 text-xs font-bold tracking-[.22em] text-indigo-700"><TrendingUp className="h-4 w-4" />MEMBER DECISION LAB</p><h1 className="mt-4 text-4xl font-black tracking-tight text-slate-950 sm:text-6xl">一分改變分析</h1><p className="mt-5 max-w-2xl text-sm font-medium leading-7 text-slate-600 sm:text-base">用你的目前條件重跑情境，清楚看見一項成績改變後，哪些校科會進入、離開或改變落點區間。</p></div></div></header>

    <section className="mt-5 grid gap-3 md:grid-cols-3" aria-label="使用方式"><Step no="1" title="選一個改變" text="提高或降低任一科。" /><Step no="2" title="重新計算" text="沿用這次分析的條件。" /><Step no="3" title="閱讀差異" text="查看增減校科與限制。" /></section>

    {member === null ? <LoadingState /> : !member ? <LockedState /> : <div className="mt-6 grid gap-6 xl:grid-cols-[320px_minmax(0,1fr)]">
      <aside className="space-y-4"><section className="rounded-2xl border-2 border-slate-900 bg-white p-5 shadow-[4px_4px_0_#0f172a]"><p className="text-xs font-black tracking-[.14em] text-slate-500">本次分析基準</p><h2 className="mt-2 text-xl font-black">目前成績</h2><div className="mt-4 grid grid-cols-3 gap-2">{subjects.map((subject) => <div key={subject.id} className="rounded-xl border border-slate-200 bg-slate-50 p-2.5"><p className="text-[11px] font-black text-slate-500">{subject.label}</p><p className="mt-1 text-lg font-black">{String(scores[subject.id] ?? '--')}</p></div>)}</div><div className="mt-4 border-t border-slate-100 pt-4 text-sm font-bold text-slate-600"><p>目前符合：<strong className="text-slate-950">{stored.results.eligibleSchools?.length || 0} 所</strong></p><p className="mt-1">篩選條件會一併保留。</p></div></section><section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold leading-6 text-amber-950"><div className="flex items-center gap-2 font-black"><Lightbulb className="h-4 w-4" />怎麼看結果？</div><p className="mt-2">「可能新增」表示依本站目前資料重新計算後進入清單，不等於保證錄取。</p></section></aside>
      <section className="min-w-0"><section className="rounded-2xl border-2 border-slate-900 bg-white p-5 shadow-[4px_4px_0_#0f172a] sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black tracking-[.14em] text-violet-700">WHAT IF</p><h2 className="mt-1 text-2xl font-black">選擇要模擬的成績</h2></div>{isScenarioLocked ? <button type="button" onClick={() => { setResult(null); setError(''); }} className="inline-flex shrink-0 items-center gap-1 text-xs font-black text-slate-500 hover:text-slate-900"><RotateCcw className="h-3.5 w-3.5" />重新選擇</button> : <p className="shrink-0 text-sm font-bold text-slate-500">一次只改一個項目</p>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{subjects.map((subject) => { const compositionScore = Number(scores.composition); const grade = String(scores[subject.id] || ''); const canIncrease = subject.id === 'composition' ? compositionScore < 6 : grade !== 'A++'; const canDecrease = subject.id === 'composition' ? compositionScore > 0 : grade !== 'C'; return <article key={subject.id} className="rounded-xl border-2 border-slate-200 bg-slate-50 p-3"><div className="flex items-baseline justify-between"><h3 className="font-black">{subject.label}</h3><span className="text-sm font-bold text-slate-500">目前 {String(scores[subject.id] ?? '--')}</span></div><div className={`mt-3 grid gap-2 ${canIncrease && canDecrease ? 'grid-cols-2' : 'grid-cols-1'}`}>{canIncrease && <ScenarioButton label="提高一級" icon={<ArrowUp className="h-3.5 w-3.5" />} tone="up" loading={loading === `${subject.id}-increase`} disabled={Boolean(loading) || isScenarioLocked} onClick={() => runScenario(subject.id, 'increase')} />}{canDecrease && <ScenarioButton label="降低一級" icon={<ArrowDown className="h-3.5 w-3.5" />} tone="down" loading={loading === `${subject.id}-decrease`} disabled={Boolean(loading) || isScenarioLocked} onClick={() => runScenario(subject.id, 'decrease')} />}</div></article>; })}</div></section>
      {error && <p role="alert" className="mt-4 rounded-xl border-2 border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-800">{error}</p>}
      <div ref={resultRef}>{result ? <ResultPanel result={result} /> : <section className="mt-6 rounded-2xl border-2 border-dashed border-slate-300 bg-white px-6 py-12 text-center"><TrendingUp className="mx-auto h-8 w-8 text-violet-600" /><h2 className="mt-3 text-xl font-black">從一個科目開始</h2><p className="mx-auto mt-2 max-w-md text-sm font-bold leading-6 text-slate-500">選擇上方任一個提高或降低情境，系統會以相同條件做前後比較。</p></section>}</div>
      {history.length > 0 && <section className="mt-6 rounded-2xl border-2 border-slate-900 bg-white p-5 shadow-[4px_4px_0_#0f172a]"><div className="flex items-center justify-between"><h2 className="font-black">本次比較紀錄</h2><button type="button" onClick={() => setHistory([])} className="inline-flex items-center gap-1 text-xs font-black text-slate-500 hover:text-slate-900"><RotateCcw className="h-3.5 w-3.5" />清除</button></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{history.map((item) => <button type="button" key={item.id} onClick={() => setResult(item)} className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-left transition hover:border-violet-300 hover:bg-violet-50"><p className="font-black">{item.label}</p><p className="mt-1 text-xs font-bold text-slate-500">{item.before.count} → {item.after.count} 所符合</p></button>)}</div></section>}
      </section>
    </div>}
    <section className="mt-8 overflow-hidden rounded-2xl border-2 border-slate-900 bg-white shadow-[5px_5px_0_#0f172a]" aria-labelledby="score-change-notes-title"><div className="border-b-2 border-slate-900 bg-amber-100 px-5 py-4 sm:px-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border-2 border-slate-900 bg-white text-amber-700"><BookOpenCheck className="h-5 w-5" /></span><div><p className="text-[10px] font-black tracking-[.18em] text-amber-800">READ BEFORE YOU DECIDE</p><h2 id="score-change-notes-title" className="mt-0.5 text-xl font-black text-slate-900">分析使用提醒</h2></div></div></div><div className="grid divide-y-2 divide-slate-900/10 sm:grid-cols-3 sm:divide-x-2 sm:divide-y-0"><div className="p-5"><span className="text-xs font-black text-indigo-700">01 · 資料基礎</span><p className="mt-2 text-sm font-bold leading-6 text-slate-700">依本站已收錄的歷年門檻與你本次篩選條件重新計算。</p></div><div className="p-5"><span className="text-xs font-black text-rose-700">02 · 未納入項目</span><p className="mt-2 text-sm font-bold leading-6 text-slate-700">不包含其他考生選填、名額異動、特殊資格與完整超額比序。</p></div><div className="p-5"><span className="text-xs font-black text-emerald-700">03 · 最後確認</span><p className="mt-2 text-sm font-bold leading-6 text-slate-700">正式選填前，務必回到當年度招生簡章與官方系統確認。</p></div></div></section>
  </div></main>;
}

function Step({ no, title, text }: { no: string; title: string; text: string }) { return <div className="relative overflow-hidden rounded-2xl border-2 border-slate-900 bg-white p-5 shadow-[4px_4px_0_#0f172a]"><span className="absolute right-4 top-1 text-5xl font-black text-indigo-50">{no}</span><div className="relative"><span className="inline-flex rounded-md bg-indigo-50 px-2 py-1 text-[10px] font-bold tracking-[.16em] text-indigo-700">STEP {no}</span><h2 className="mt-3 text-lg font-black text-slate-900">{title}</h2><p className="mt-1 text-sm font-medium leading-6 text-slate-500">{text}</p></div></div>; }
function ScenarioButton({ label, icon, tone, loading, disabled, onClick }: { label: string; icon: React.ReactNode; tone: 'up' | 'down'; loading: boolean; disabled: boolean; onClick: () => void }) { const style = tone === 'up' ? 'border-emerald-300 bg-emerald-50 text-emerald-800 hover:bg-emerald-100' : 'border-rose-300 bg-rose-50 text-rose-800 hover:bg-rose-100'; return <button type="button" onClick={onClick} disabled={disabled} className={`inline-flex items-center justify-center gap-1 rounded-lg border px-2 py-2 text-xs font-black transition disabled:opacity-50 ${style}`}>{loading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : icon}{label}</button>; }
function ResultPanel({ result }: { result: ChangeResult }) { return <section className="mt-6 overflow-hidden rounded-2xl border-2 border-slate-900 bg-white shadow-[4px_4px_0_#0f172a]"><header className="border-b-2 border-slate-900 bg-violet-50 p-5"><p className="text-xs font-black tracking-[.14em] text-violet-700">SIMULATION RESULT</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><h2 className="text-2xl font-black">{result.label}</h2><p className="text-sm font-bold text-slate-600">符合校科 <strong className="text-xl text-slate-950">{result.before.count} → {result.after.count}</strong> 所</p></div></header><div className="grid gap-4 p-5 md:grid-cols-2"><ChangeList title="可能新增的校科" schools={result.added} tone="emerald" empty="依目前資料與條件，沒有新增校科。" showZone /><ChangeList title="可能移出的校科" schools={result.removed} tone="rose" empty="依目前資料與條件，沒有移出校科。" /></div><div className="border-t border-slate-200 bg-slate-50 p-5"><ZoneChangeList changes={result.zoneChanges} /></div></section>; }
function ZoneChangeList({ changes }: { changes: ZoneChange[] }) { return <section><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="font-black text-slate-900">落點區間變化</h3><p className="text-xs font-bold text-slate-500">同一校科仍在清單內，但參考區間已改變</p></div>{changes.length ? <ul className="mt-3 grid gap-2 sm:grid-cols-2">{changes.map((school) => <li key={`${school.name}-${school.district}-${school.type}`} className="rounded-xl border border-violet-200 bg-white p-3"><p className="font-black text-slate-900">{school.name}</p><div className="mt-2 flex items-center gap-2 text-xs font-black"><span className="rounded bg-slate-100 px-2 py-1 text-slate-600">{zoneText[school.fromZone] || school.fromZone}</span><ArrowRight className="h-3.5 w-3.5 text-violet-600" /><span className="rounded bg-violet-100 px-2 py-1 text-violet-800">{zoneText[school.toZone] || school.toZone}</span></div></li>)}</ul> : <p className="mt-3 text-sm font-bold text-slate-500">這次變動沒有讓既有校科改變落點區間。</p>}</section>; }
function ChangeList({ title, schools, tone, empty, showZone = false }: { title: string; schools: SchoolChange[]; tone: 'emerald' | 'rose'; empty: string; showZone?: boolean }) { const style = tone === 'emerald' ? 'border-emerald-200 bg-emerald-50 text-emerald-950' : 'border-rose-200 bg-rose-50 text-rose-950'; return <section className={`rounded-xl border p-4 ${style}`}><h3 className="font-black">{title}（{schools.length}）</h3>{schools.length ? <ul className="mt-3 space-y-2">{schools.map((school) => <li key={`${school.name}-${school.district}-${school.type}`} className="flex flex-wrap items-center gap-2 rounded-lg bg-white/80 px-3 py-2.5 text-sm font-bold"><span>{school.name}</span>{showZone && <span className={`ml-auto rounded-md border px-2 py-1 text-[11px] font-black ${school.zone === 'safe' ? 'border-emerald-300 bg-emerald-100 text-emerald-800' : school.zone === 'target' ? 'border-sky-300 bg-sky-100 text-sky-800' : 'border-rose-300 bg-rose-100 text-rose-800'}`}>{zoneText[school.zone] || school.zone}</span>}</li>)}</ul> : <p className="mt-3 text-sm font-bold opacity-75">{empty}</p>}</section>; }
function LoadingState() { return <section className="mt-6 rounded-2xl border-2 border-slate-900 bg-white p-8 text-center font-bold text-slate-500 shadow-[4px_4px_0_#0f172a]"><Loader2 className="mx-auto h-6 w-6 animate-spin" /> <p className="mt-3">正在確認會員資格…</p></section>; }
function LockedState() { return <section className="mt-6 overflow-hidden rounded-2xl border-2 border-slate-900 bg-white shadow-[5px_5px_0_#0f172a]"><div className="bg-violet-50 p-6 sm:p-8"><p className="text-xs font-black tracking-[.16em] text-violet-700">MEMBER PREVIEW</p><h2 className="mt-2 text-3xl font-black">一科改變，選擇可能差很多。</h2><p className="mt-3 max-w-2xl text-sm font-bold leading-7 text-slate-600">會員可對六科逐一提高或降低，直接查看自己的校科增減清單，不必猜測哪一科最值得努力。</p><a href={withBasePath('/membership')} className="mt-6 inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-amber-300 px-5 py-3 font-black text-slate-900 shadow-[3px_3px_0_#0f172a]"><LockKeyhole className="h-4 w-4" />解鎖一分改變分析</a></div><div className="grid gap-3 p-5 sm:grid-cols-3"><Preview title="六科都能選" text="提高或降低一級。" /><Preview title="你的條件" text="保留本次就學區與篩選。" /><Preview title="明確差異" text="直接列出校科增減。" /></div></section>; }
function Preview({ title, text }: { title: string; text: string }) { return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><BadgeCheck className="h-5 w-5 text-emerald-600" /><h3 className="mt-2 font-black">{title}</h3><p className="mt-1 text-sm font-bold text-slate-500">{text}</p></div>; }
function EmptyState() { return <main className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900"><section className="mx-auto max-w-xl rounded-2xl border-2 border-slate-900 bg-white p-8 text-center shadow-[5px_5px_0_#0f172a]"><TrendingUp className="mx-auto h-10 w-10 text-violet-600" /><h1 className="mt-4 text-2xl font-black">先完成一次落點分析</h1><p className="mt-2 text-sm font-bold leading-6 text-slate-600">一分改變分析會以你最近一次的成績、考區與篩選條件作為基準。</p><a href={withBasePath('/')} className="mt-6 inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-indigo-600 px-5 py-3 font-black text-white"><ArrowLeft className="h-4 w-4" />開始落點分析</a></section></main>; }
