begin;
delete from public.schools;
insert into public.schools (region,name,points,credits,type,ownership,vocational_group,min_chinese,min_english,min_math,min_science,min_social) values
('taoyuan','武陵高中(普通科)',33,31,'普通科','public','學術群',9,8,8,null,null),
('taoyuan','中壢高中(普通科)',31,27,'普通科','public','學術群',8,null,7,null,null),
('taoyuan','桃園高中(普通科)',29,27,'普通科','public','學術群',9,6,6,null,8),
('taoyuan','內壢高中(普通科)',29,23,'普通科','public','學術群',7,6,6,null,null),
('taoyuan','復旦高中(普通科)',27,21,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','陽明高中(普通科)',27,19,'普通科','public','學術群',6,null,7,null,null),
('taoyuan','平鎮高中(普通科)',25,21,'普通科','public','學術群',7,null,null,null,null),
('taoyuan','永豐高中(普通科)',25,18,'普通科','public','學術群',6,null,7,null,null),
('taoyuan','北科附工(電機科)',25,18,'職業類科','public','電機與電子群',null,null,null,null,null),
('taoyuan','中壢高商(綜合科)',25,16,'普通科','public','學術群',6,null,null,null,null),
('taoyuan','北科附工(畜產保健)',25,14,'職業類科','public','農業群',null,null,null,null,null),
('taoyuan','北科附工(電子科)',25,13,'職業類科','public','電機與電子群',null,null,null,null,null),
('taoyuan','大園高中(普通科)',23,17,'普通科','public','學術群',6,null,4,null,null),
('taoyuan','南崁高中(普通科)',23,17,'普通科','public','學術群',6,null,5,null,null),
('taoyuan','壽山高中(普通科)',23,16,'普通科','public','學術群',6,6,5,null,null),
('taoyuan','龍潭高中(普通科)',23,15,'普通科','public','學術群',6,null,6,null,null),
('taoyuan','振聲高中(普通科)',23,15,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','北科附工(化工科)',23,15,'職業類科','public','化工群',null,null,null,null,null),
('taoyuan','中壢高商(商業經營科)',23,14,'職業類科','public','商業與管理群',null,null,null,null,null),
('taoyuan','中壢家商(應用英語科)',23,14,'職業類科','public','外語群',null,null,null,null,null),
('taoyuan','北科附工(機械科)',23,14,'職業類科','public','機械群',null,null,null,null,null),
('taoyuan','北科附工(動力機械)',23,14,'職業類科','public','動力機械群',null,null,null,null,null),
('taoyuan','六和高中(普通科)',23,13,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','壽山高中(應用英語科)',23,13,'職業類科','public','外語群',null,null,null,null,null),
('taoyuan','龍潭高中(電子科)',23,13,'職業類科','public','電機與電子群',null,null,null,null,null),
('taoyuan','龍潭高中(電機科)',23,13,'職業類科','public','電機與電子群',null,null,null,null,null),
('taoyuan','振聲高中(應用英語科)',23,13,'職業類科','private','外語群',null,null,null,null,null),
('taoyuan','新興高中(應用日語科)',23,13,'職業類科','private','外語群',null,null,null,null,null),
('taoyuan','六和高中(機電科)',23,13,'普通科','private','機械群',null,null,null,null,null),
('taoyuan','六和高中(資訊科)',23,13,'普通科','private','電機與電子群',null,null,null,null,null),
('taoyuan','六和高中( 應用英語科)',23,13,'普通科','private','外語群',null,null,null,null,null),
('taoyuan','六和高中( 多媒體設計科)',23,13,'普通科','private','設計群',null,null,null,null,null),
('taoyuan','中壢高商(資料處理科)',23,12,'職業類科','public','商業與管理群',null,null,null,null,null),
('taoyuan','壽山高中(國際貿易)',23,12,'職業類科','public','商業與管理群',null,null,null,null,null),
('taoyuan','楊梅高中(普通科)',23,11,'普通科','public','學術群',4,4,4,null,5),
('taoyuan','壽山高中(廣告設計科)',23,11,'職業類科','public','設計群',null,null,null,null,null),
('taoyuan','北科附工(汽車科)',23,11,'職業類科','public','動力機械群',null,null,null,null,null),
('taoyuan','振聲高中(資訊科)',23,11,'職業類科','private','電機與電子群',null,null,null,null,null),
('taoyuan','中壢高商(國際貿易科)',23,10,'職業類科','public','商業與管理群',null,null,null,null,null),
('taoyuan','中壢家商(資料處理科)',23,10,'職業類科','public','商業與管理群',null,null,null,null,null),
('taoyuan','中壢家商(家政科)',23,10,'職業類科','public','家政群',null,null,null,null,null),
('taoyuan','北科附工(模具科)',23,10,'職業類科','public','機械群',null,null,null,null,null),
('taoyuan','北科附工(農場經營科)',23,10,'職業類科','public','農業群',null,null,null,null,null),
('taoyuan','龍潭高中(畜產保健科)',23,10,'職業類科','public','農業群',null,null,null,null,null),
('taoyuan','振聲高中(商業經營科)',23,10,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','啟英高中(資料處理科)',22,10,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','龍潭高中(機械科)',21,15,'職業類科','public','機械群',null,null,null,null,null),
('taoyuan','北科附工(生物產業機電)',21,14,'職業類科','public','機械群',null,null,null,null,null),
('taoyuan','中壢家商(商業經營科)',21,13,'職業類科','public','商業與管理群',null,null,null,null,null),
('taoyuan','北科附工(園藝科)',21,13,'職業類科','public','農業群',null,null,null,null,null),
('taoyuan','楊梅高中(電子科)',21,12,'職業類科','public','電機與電子群',null,null,null,null,null),
('taoyuan','楊梅高中(資訊科)',21,12,'職業類科','public','電機與電子群',null,null,null,null,null),
('taoyuan','振聲高中(觀光事業科)',21,12,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','觀音高中(普通科)',21,11,'普通科','public','學術群',5,null,4,null,null),
('taoyuan','育達高中(普通科)',21,11,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','大溪高中(普通科)',21,10,'普通科','public','學術群',null,null,null,null,null),
('taoyuan','龍潭高中(造園科)',21,10,'職業類科','public','設計群',null,null,null,null,null),
('taoyuan','關西高中(家政科)',21,10,'職業類科','public','家政群',null,null,null,null,null),
('taoyuan','新興高中(普通科)',21,9,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','新屋高中(普通科)',21,9,'普通科','public','學術群',null,null,null,null,null),
('taoyuan','中壢家商(服裝設計科)',21,9,'職業類科','public','家政群',null,null,null,null,null),
('taoyuan','關西高中(園藝科)',21,9,'職業類科','public','農業群',null,null,null,null,null),
('taoyuan','振聲高中(電子商務科)',21,9,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','振聲高中(多媒體設計)',21,9,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','啟英高中(室內設計科)',21,9,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','育達高中(資訊科)',21,9,'職業類科','private','電機與電子群',null,null,null,null,null),
('taoyuan','觀音高中(化工科)',21,9,'職業類科','public','化工群',null,null,null,null,null),
('taoyuan','光啟高中( 普通科)',21,9,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','大華高中(普通科)',21,9,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','育達高中(廣告設計科)',19,10,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','新興高中(資料處理科)',19,9,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','新興高中(應用英語科)',19,9,'職業類科','private','外語群',null,null,null,null,null),
('taoyuan','新興高中(電子科)',19,9,'職業類科','private','電機與電子群',null,null,null,null,null),
('taoyuan','新興高中(廣告設計科)',19,9,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','新興高中(機械科)',19,9,'職業類科','private','機械群',null,null,null,null,null),
('taoyuan','治平高中(普通科)',19,8,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','啟英高中(普通科)',19,8,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','龍潭高中(園藝科)',19,8,'職業類科','public','農業群',null,null,null,null,null),
('taoyuan','關西高中(畜產保健科)',19,8,'職業類科','public','農業群',null,null,null,null,null),
('taoyuan','新興高中(飛機修護科)',19,8,'職業類科','private','動力機械群',null,null,null,null,null),
('taoyuan','新興高中(觀光事業科)',19,8,'職業類科','private','餐旅群',null,null,null,null,null),
('taoyuan','新興高中(電子商務科)',19,8,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','新興高中(家具木工科)',19,8,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','啟英高中(應用英語科)',19,8,'職業類科','private','外語群',null,null,null,null,null),
('taoyuan','育達高中(商業經營科)',19,8,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','育達高中(應用英語科)',19,8,'職業類科','private','外語群',null,null,null,null,null),
('taoyuan','育達高中(幼兒保育科)',19,8,'職業類科','private','家政群',null,null,null,null,null),
('taoyuan','育達高中(會計事務科)',19,8,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','光啟高中(機械科)',19,8,'職業類科','private','機械群',null,null,null,null,null),
('taoyuan','光啟高中(汽車科)',19,8,'職業類科','private','動力機械群',null,null,null,null,null),
('taoyuan','光啟高中(電機科)',19,8,'職業類科','private','電機與電子群',null,null,null,null,null),
('taoyuan','光啟高中(資訊科)',19,8,'職業類科','private','電機與電子群',null,null,null,null,null),
('taoyuan','光啟高中(餐飲管理科)',19,8,'職業類科','private','餐旅群',null,null,null,null,null),
('taoyuan','清華高中( 軌道車輛科)',19,8,'職業類科','private','動力機械群',null,null,null,null,null),
('taoyuan','清華高中(  汽車科)',19,8,'職業類科','private','動力機械群',null,null,null,null,null),
('taoyuan','清華高中( 餐飲管理科)',19,8,'職業類科','private','餐旅群',null,null,null,null,null),
('taoyuan','羅浮高中( 餐飲管理科)',19,8,'職業類科','public','餐旅群',null,null,null,null,null),
('taoyuan','羅浮高中(  觀光事業科)',19,8,'職業類科','public','餐旅群',null,null,null,null,null),
('taoyuan','啟英高中(汽車科)',18,8,'職業類科','private','動力機械群',null,null,null,null,null),
('taoyuan','新興高中(汽車科)',17,9,'職業類科','private','動力機械群',null,null,null,null,null),
('taoyuan','啟英高中(汽車科)',17,8,'職業類科','private','動力機械群',null,null,null,null,null),
('taoyuan','啟英高中(資訊科)',17,8,'職業類科','private','電機與電子群',null,null,null,null,null),
('taoyuan','至善高中(  家具木工科)',17,8,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','至善高中(   幼兒保育科)',17,8,'職業類科','private','家政群',null,null,null,null,null),
('taoyuan','至善高中(  普通科)',17,8,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','至善高中(   農產行銷科)',17,8,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','至善高中(  觀光事業科)',17,8,'職業類科','private','餐旅群',null,null,null,null,null),
('taoyuan','永平工商(餐飲管理科)',17,7,'職業類科','private','餐旅群',null,null,null,null,null),
('taoyuan','永平工商(觀光事業科)',17,7,'職業類科','private','餐旅群',null,null,null,null,null),
('taoyuan','永平工商(表演藝術科)',17,7,'職業類科','private','藝術群',null,null,null,null,null),
('taoyuan','永平工商(汽車科)',17,7,'職業類科','private','動力機械群',null,null,null,null,null),
('taoyuan','永平工商(資料處理科)',17,7,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','永平工商(幼兒保育科)',17,7,'職業類科','private','家政群',null,null,null,null,null),
('taoyuan','永平工商(廣告設計科)',17,7,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','育達高中(餐飲管理科)',17,5,'職業類科','private','餐旅群',null,null,null,null,null),
('taoyuan','育達高中(多媒體設計科)',17,5,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','育達高中(觀光事業科)',16,9,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','育達高中(應用日語科)',16,8,'職業類科','private','外語群',null,null,null,null,null),
('taoyuan','啟英高中(資訊科)',16,7,'職業類科','private','電機與電子群',null,null,null,null,null),
('taoyuan','啟英高中(室內設計科)',15,7,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','治平高中(綜合科)',15,6,'普通科','private','學術群',null,null,null,null,null),
('taoyuan','啟英高中(餐飲管理科)',15,6,'職業類科','private','餐旅群',null,null,null,null,null),
('taoyuan','啟英高中(時尚造型科)',15,6,'職業類科','private','家政群',null,null,null,null,null),
('taoyuan','啟英高中(應用外語科(日文組))',14,6,'職業類科','private','外語群',null,null,null,null,null),
('taoyuan','啟英高中(餐飲管理科)',14,6,'職業類科','private','餐飲管理科',null,null,null,null,null),
('taoyuan','啟英高中(資料處理科)',13,6,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','啟英高中(電子商務科)',13,6,'職業類科','private','商業與管理群',null,null,null,null,null),
('taoyuan','啟英高中(廣告設計科)',13,6,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','啟英高中(電影電視科)',13,6,'職業類科','private','設計群',null,null,null,null,null),
('taoyuan','啟英高中(應用外語科(英文組)',13,5,'職業類科','private','外語群',null,null,null,null,null),
('taoyuan','啟英高中(時尚造型科)',13,5,'職業類科','private','設計群',null,null,null,null,null),
('kaohsiung','市立高雄中學（普通科）',30,30,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立高雄女中（普通科）',30,25,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','國立高師大附中（普通科）',28,30,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','國立鳳山高中（普通科）',28,27,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立新莊高中（普通科）',26,25,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','國立鳳新高中（普通科）',26,23,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','國立中山大學附屬高中（普通科）',24,24,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立瑞祥高中（普通科）',24,21,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立中正高中（普通科）',22,23,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立新興高中（普通科）',22,21,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立三民高中（普通科）',22,19,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立高雄高工（電機科）',22,19,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','市立前鎮高中（普通科）',22,16,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立高雄高工（電子科）',22,16,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','市立福誠高中（普通科）',22,15,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','國立高餐大附屬餐旅中學（餐飲管理科）',22,15,'職業類科','public','餐旅群',null,null,null,null,null),
('kaohsiung','市立高雄高工（資訊科）',22,14,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','市立文山高中（普通科）',20,20,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','私立復華高中（普通科）',20,19,'普通科','private','學術群',null,null,null,null,null),
('kaohsiung','市立中山高中（普通科）',20,17,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立高雄高工（化工科）',20,17,'職業類科','public','化工群',null,null,null,null,null),
('kaohsiung','市立高雄高工（汽車科）',20,16,'職業類科','public','動力機械群',null,null,null,null,null),
('kaohsiung','市立高雄高商（廣告設計科）',20,15,'職業類科','public','設計群',null,null,null,null,null),
('kaohsiung','市立左營高中（普通科）',20,14,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立高雄高工（機械科）',20,14,'職業類科','public','機械群',null,null,null,null,null),
('kaohsiung','市立高雄高工（建築科）',20,14,'職業類科','public','土木與建築群',null,null,null,null,null),
('kaohsiung','市立三民家商（幼兒保育科）',20,14,'職業類科','public','家政群',null,null,null,null,null),
('kaohsiung','市立小港高中（普通科）',20,13,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立高雄高工（圖文傳播科）',20,13,'職業類科','public','設計群',null,null,null,null,null),
('kaohsiung','市立三民家商（餐飲管理科）',20,13,'職業類科','public','餐旅群',null,null,null,null,null),
('kaohsiung','市立三民家商（室內設計科）',20,13,'職業類科','public','設計群',null,null,null,null,null),
('kaohsiung','市立高雄高工（冷凍空調科）',20,13,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','市立三民家商（資料處理科）',20,13,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','市立高雄高工（建築製圖科）',20,13,'職業類科','public','機械群',null,null,null,null,null),
('kaohsiung','市立高雄高商（商業經營科）',20,12,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','市立中正高工（電機科）',20,12,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','市立三民家商（美容科）',20,12,'職業類科','public','家政群',null,null,null,null,null),
('kaohsiung','市立中正高工（電子科）',20,11,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','私立立志高中（普通科）',20,11,'普通科','private','學術群',null,null,null,null,null),
('kaohsiung','私立立志高中（電機科）',20,11,'職業類科','private','電機與電子群',null,null,null,null,null),
('kaohsiung','市立鼓山高中（普通科）',20,10,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立高雄高商（國際貿易科）',20,10,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','市立高雄高商（資料處理科）',20,10,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','市立三民家商（國際貿易科）',20,10,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','市立海青工商（室內空間設計科）',20,10,'職業類科','public','設計群',null,null,null,null,null),
('kaohsiung','市立三民家商（服裝科）',20,10,'職業類科','public','家政群',null,null,null,null,null),
('kaohsiung','國立鳳山商工（會計事務科）',18,14,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','市立中正高工（資訊科）',18,12,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','國立鳳山商工（家具設計科）',18,12,'職業類科','public','設計群',null,null,null,null,null),
('kaohsiung','國立鳳山商工（資料處理科）',18,11,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','市立海青工商（電子科）',18,11,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','國立鳳山商工（機械科）',18,11,'職業類科','public','機械群',null,null,null,null,null),
('kaohsiung','私立中華藝校（影劇科）',18,11,'職業類科','private','藝術群',null,null,null,null,null),
('kaohsiung','市立高雄高商（會計事務科）',18,10,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','國立鳳山商工（國際貿易科）',18,10,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','國立鳳山商工（室內空間設計科）',18,10,'職業類科','public','設計群',null,null,null,null,null),
('kaohsiung','市立中正高工（化工科）',18,10,'職業類科','public','化工群',null,null,null,null,null),
('kaohsiung','市立中正高工（控制科）',18,10,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','市立中正高工（金屬工藝科）',18,10,'職業類科','public','設計群',null,null,null,null,null),
('kaohsiung','市立海青工商（會計事務科）',18,9,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','私立中華藝校（多媒體動畫科）',18,9,'職業類科','private','藝術群',null,null,null,null,null),
('kaohsiung','市立海青工商（廣告設計科）',16,11,'職業類科','public','設計群',null,null,null,null,null),
('kaohsiung','市立中正高工（機械科）',16,9,'職業類科','public','機械群',null,null,null,null,null),
('kaohsiung','國立鳳山商工（商業經營科）',16,9,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','市立中正高工（汽車科）',16,9,'職業類科','public','動力機械群',null,null,null,null,null),
('kaohsiung','市立中正高工（製圖科）',16,9,'職業類科','public','機械群',null,null,null,null,null),
('kaohsiung','私立中山工商（電機科）',16,9,'職業類科','private','電機與電子群',null,null,null,null,null),
('kaohsiung','私立中山工商（餐飲管理科）',16,9,'職業類科','private','餐旅群',null,null,null,null,null),
('kaohsiung','國立岡山高中（普通科）',16,8,'普通科','public','學術群',null,null,null,null,null);
insert into public.schools (region,name,points,credits,type,ownership,vocational_group,min_chinese,min_english,min_math,min_science,min_social) values
('kaohsiung','市立海青工商（美工科）',16,8,'職業類科','public','設計群',null,null,null,null,null),
('kaohsiung','市立海青工商（資料處理科）',16,8,'職業類科','public','商業與管理群',null,null,null,null,null),
('kaohsiung','市立中正高工（建築科）',16,8,'職業類科','public','土木與建築群',null,null,null,null,null),
('kaohsiung','國立岡山農工（電子科）',16,8,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','私立三信家商（應用日語科）',16,8,'職業類科','private','外語群',null,null,null,null,null),
('kaohsiung','私立中山工商（資訊科）',16,8,'職業類科','private','電機與電子群',null,null,null,null,null),
('kaohsiung','國立岡山農工（化工科）',14,8,'職業類科','public','化工群',null,null,null,null,null),
('kaohsiung','市立海青工商（資訊科）',14,7,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','市立海青工商（建築科）',14,7,'職業類科','public','土木與建築群',null,null,null,null,null),
('kaohsiung','天主教道明中學（普通科）',14,7,'普通科','private','學術群',null,null,null,null,null),
('kaohsiung','私立樹德家商（廣告設計科）',14,7,'職業類科','private','設計群',null,null,null,null,null),
('kaohsiung','私立樹德家商（商業經營科）',14,7,'職業類科','private','商業與管理群',null,null,null,null,null),
('kaohsiung','市立仁武高中（普通科）',12,6,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立中正高工（冷凍空調科）',12,6,'職業類科','public','電機與電子群',null,null,null,null,null),
('kaohsiung','私立樹德家商（資料處理科）',12,6,'職業類科','private','商業與管理群',null,null,null,null,null),
('kaohsiung','私立樹德家商（美容科）',12,6,'職業類科','private','家政群',null,null,null,null,null),
('kaohsiung','私立樹德家商（幼兒保育科）',12,6,'職業類科','private','家政群',null,null,null,null,null),
('kaohsiung','市立楠梓高中（綜合科）',10,5,'普通科','public','學術群',null,null,null,null,null),
('kaohsiung','市立海青工商（土木科）',10,5,'職業類科','public','土木與建築群',null,null,null,null,null),
('kaohsiung','私立立志高中進修學校（汽車科）',10,5,'職業類科','private','動力機械群',null,null,null,null,null),
('kaohsiung','私立樹德家商（餐飲管理科）',10,5,'職業類科','private','餐旅群',null,null,null,null,null),
('kaohsiung','私立立志高中（餐飲管理科）',10,5,'職業類科','private','餐旅群',null,null,null,null,null),
('kaohsiung','私立樹德家商（表演藝術科）',10,5,'職業類科','private','藝術群',null,null,null,null,null),
('kaohsiung','私立樹德家商（照顧服務科）',10,5,'職業類科','private','家政群',null,null,null,null,null),
('central','國立臺中第一高級中學（普通科）',30,95,'普通科','public','學術群',null,null,null,null,null),
('central','國立臺中女子高級中學（普通科）',30,92,'普通科','public','學術群',null,null,null,null,null),
('central','國立中科實驗高級中學（普通科）',30,91,'普通科','public','學術群',null,null,null,null,null),
('central','國立中興大學附屬高級中學（普通科）',28,95,'普通科','public','學術群',null,null,null,null,null),
('central','國立文華高級中學（普通科）',28,85,'普通科','public','學術群',null,null,null,null,null),
('central','臺中市立惠文高級中學（普通科）',28,79,'普通科','public','學術群',null,null,null,null,null),
('central','私立明道高級中學（普通科）',26,82,'普通科','private','學術群',null,null,null,null,null),
('central','私立曉明女子高級中學（普通科）',26,79,'普通科','private','學術群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（電機科）',26,76,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','臺中市立臺中第二高級中學（普通科）女',26,71,'普通科','public','學術群',null,null,null,null,null),
('central','臺中市私立忠民高級中學（普通科）',26,70,'普通科','public','學術群',null,null,null,null,null),
('central','臺中市立臺中第二高級中學（普通科）男',26,69,'普通科','public','學術群',null,null,null,null,null),
('central','臺中市立東山高級中學（普通科）',24,70,'普通科','public','學術群',null,null,null,null,null),
('central','臺中市立西苑高級中學（普通科）',24,70,'普通科','public','學術群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（電子科）',24,70,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（資訊科）',24,67,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','國立臺中教育大學附設高級中學（普通科）',24,66,'普通科','private','學術群',null,null,null,null,null),
('central','國立中興大學附屬農業高級中學（餐飲管理科）',24,64,'職業類科','public','餐旅群',null,null,null,null,null),
('central','私立衛道高級中學',24,64,'普通科','private','學術群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（建築科）',24,64,'職業類科','public','土木與建築群',null,null,null,null,null),
('central','臺中市立臺中大里高級中學（普通科）',24,61,'普通科','public','學術群',null,null,null,null,null),
('central','私立僑泰高級中學（多媒體設計科）',23,43,'職業類科','private','設計群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（控制科）',22,67,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','國立臺中高級家事商業職業學校（商業經營科）',22,65,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（化工科）',22,64,'職業類科','public','化工群',null,null,null,null,null),
('central','國立中興大學附屬農業高級中學（畜產保健科）',22,62,'職業類科','public','農業群',null,null,null,null,null),
('central','國立中興高級中學（普通科）〔南投〕',22,61,'普通科','public','學術群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（機械科）',22,61,'職業類科','public','機械群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（圖文傳播科）',22,61,'職業類科','public','設計群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（土木科）',22,60,'職業類科','public','土木與建築群',null,null,null,null,null),
('central','臺中市立豐原高級中學',22,58,'普通科','public','學術群',null,null,null,null,null),
('central','國立臺中高級家事商業職業學校（國際貿易科）',22,56,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','私立僑泰高級中學（應用英語科）',22,55,'職業類科','private','外語群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（冷凍空調科）',22,55,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','私立長億高級中學（普通科）',22,53,'普通科','public','學術群',null,null,null,null,null),
('central','國立沙鹿高級工業職業學校（資訊科）',22,53,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','國立臺中高級家事商業職業學校（會計事務科）',22,52,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','國立沙鹿高級工業職業學校（電子科）',22,52,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','私立青年高級中學（電影電視科）',22,49,'職業類科','private','藝術群',null,null,null,null,null),
('central','私立明道高級中學（外語科英文組）',22,49,'職業類科','private','外語群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（電腦機械製圖科）',22,49,'職業類科','public','機械群',null,null,null,null,null),
('central','國立臺中高級家事商業職業學校（資料處理科）',22,43,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','私立嶺東高級中學（國際貿易科）',22,40,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','臺中市立清水高級中學',20,61,'普通科','public','學術群',null,null,null,null,null),
('central','國立臺中高級家事商業職業學校（流行服飾科）',20,56,'職業類科','public','家政群',null,null,null,null,null),
('central','國立中興大學附屬農業高級中學（土木科）',20,55,'職業類科','public','土木與建築群',null,null,null,null,null),
('central','國立沙鹿高級工業職業學校（染整科）',20,55,'職業類科','public','化工群',null,null,null,null,null),
('central','國立中興大學附屬農業高級中學（食品加工科）',20,53,'職業類科','public','食品群',null,null,null,null,null),
('central','私立嶺東高級中學（多媒體設計科）',20,53,'職業類科','private','設計群',null,null,null,null,null),
('central','國立中興大學附屬農業高級中學（園藝科）',20,52,'職業類科','public','農業群',null,null,null,null,null),
('central','國立中興大學附屬農業高級中學（觀光事業科）',20,52,'職業類科','public','餐旅群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（板金科）',20,51,'職業類科','public','機械群',null,null,null,null,null),
('central','私立立人高級中學（普通科）',20,49,'普通科','private','學術群',null,null,null,null,null),
('central','私立葳格高級中學（普通科）',20,49,'普通科','private','學術群',null,null,null,null,null),
('central','國立臺中高級家事商業職業學校（幼兒保育科）',20,49,'職業類科','public','家政群',null,null,null,null,null),
('central','私立僑泰高級中學（廣告設計科）',20,49,'職業類科','private','設計群',null,null,null,null,null),
('central','私立常春藤高級中學（普通科）',20,49,'普通科','public','學術群',null,null,null,null,null),
('central','臺中市立大甲高級中學（綜合高中）',20,49,'普通科','public','學術群',null,null,null,null,null),
('central','私立僑泰高級中學（資料處理科）',20,47,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','國立霧峰農工職業學校（電機科）',20,46,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','國立霧峰農工職業學校（餐飲管理科）',20,46,'職業類科','public','餐旅群',null,null,null,null,null),
('central','國立沙鹿高級工業職業學校（機械科）',20,46,'職業類科','public','機械群',null,null,null,null,null),
('central','私立明道高級中學（美工科）',20,46,'職業類科','private','設計群',null,null,null,null,null),
('central','臺中市立大甲高級工業職業學校（電機科）',20,46,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','私立新民高級中學（普通科）',20,44,'普通科','private','學術群',null,null,null,null,null),
('central','臺中市立大甲高級中學（美工科）',20,43,'職業類科','public','設計群',null,null,null,null,null),
('central','臺中市立大甲高級工業職業學校（資訊科）',20,43,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','國立霧峰農工職業學校（電子科）',20,41,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','國立南投高級中學（應用英語科）',20,41,'職業類科','public','外語群',null,null,null,null,null),
('central','國立沙鹿高級工業職業學校（製圖科）',20,41,'職業類科','public','機械群',null,null,null,null,null),
('central','私立明德高級中學（普通科）',20,40,'普通科','private','學術群',null,null,null,null,null),
('central','國立中興大學附屬農業高級中學（農場經營科）',20,40,'職業類科','public','農業群',null,null,null,null,null),
('central','國立霧峰農工職業學校（食品加工科）',20,40,'職業類科','public','食品群',null,null,null,null,null),
('central','國立霧峰農工職業學校（機械科）',20,40,'職業類科','public','機械群',null,null,null,null,null),
('central','國立草屯商工職業學校（應用英語科）〔南投〕',20,40,'職業類科','public','外語群',null,null,null,null,null),
('central','私立明德高級中學（幼兒保育科）',20,40,'職業類科','private','家政群',null,null,null,null,null),
('central','私立明德高級中學（美容科）',20,40,'職業類科','private','家政群',null,null,null,null,null),
('central','私立大明高級中學（餐飲管理科）',20,40,'職業類科','private','餐旅群',null,null,null,null,null),
('central','私立弘文高級中學（普通科）',20,40,'普通科','public','學術群',null,null,null,null,null),
('central','臺中市立大甲高級中學（普通科）',20,40,'普通科','public','學術群',null,null,null,null,null),
('central','私立明道高級中學（商業經營科）',20,40,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','私立明道高級中學（廣告設計科）',20,40,'職業類科','private','設計群',null,null,null,null,null),
('central','私立明道高級中學（觀光事業科）',20,40,'職業類科','private','餐旅群',null,null,null,null,null),
('central','臺中市立大甲高級工業職業學校（建築科）',20,40,'職業類科','public','土木與建築群',null,null,null,null,null),
('central','國立霧峰農工職業學校（汽車科）',20,37,'職業類科','public','動力機械群',null,null,null,null,null),
('central','國立霧峰農工職業學校（園藝科）',20,37,'職業類科','public','農業群',null,null,null,null,null),
('central','國立沙鹿高級工業職業學校（化工科）',20,37,'職業類科','public','化工群',null,null,null,null,null),
('central','國立沙鹿高級工業職業學校（資料處理科）',20,37,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','國立沙鹿高級工業職業學校（汽車科）',20,37,'職業類科','public','動力機械群',null,null,null,null,null),
('central','私立明道高級中學（電子科）',20,37,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','私立明道高級中學（餐飲管理科）',20,37,'職業類科','private','餐旅群',null,null,null,null,null),
('central','神岡工業高級中等學校（機械科）',20,37,'職業類科','public','動力機械群',null,null,null,null,null),
('central','南投縣立竹山高級中學（綜合高中）',20,37,'普通科','public','學術群',null,null,null,null,null),
('central','臺中市立大甲高級工業職業學校（電子科）',20,37,'職業類科','public','電機與電子群',null,null,null,null,null),
('central','私立僑泰高級中學（餐飲管理科）',20,36,'職業類科','private','餐旅群',null,null,null,null,null),
('central','私立明道高級中學（資訊科）',20,34,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（多媒體設計科）',20,34,'職業類科','private','設計群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（汽車科）',20,32,'職業類科','public','動力機械群',null,null,null,null,null),
('central','臺中市立新社高級中學（普通科）',20,31,'普通科','public','學術群',null,null,null,null,null),
('central','私立明德高級中學（多媒體設計科）',20,24,'職業類科','private','設計群',null,null,null,null,null),
('central','私立明德高級中學（資料處理科）',19,37,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','私立青年高級中學（廣告設計科）',18,47,'職業類科','private','設計群',null,null,null,null,null),
('central','私立明德高級中學（應用英語科）',18,43,'職業類科','private','外語群',null,null,null,null,null),
('central','私立嶺東高級中學（普通科）',18,40,'普通科','private','學術群',null,null,null,null,null),
('central','南投縣立旭光高級中學（普通科）',18,37,'普通科','public','學術群',null,null,null,null,null),
('central','私立僑泰高級中學（資訊科）',18,37,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','國立南投高級中學（美工科）',18,35,'職業類科','public','設計群',null,null,null,null,null),
('central','國立草屯商工職業學校（配管科）〔南投〕',18,34,'職業類科','public','機械群',null,null,null,null,null),
('central','國立草屯商工職業學校（機械科）〔南投〕',18,34,'職業類科','public','機械群',null,null,null,null,null),
('central','臺中市立大甲高級工業職業學校（製圖科）',18,34,'職業類科','public','機械群',null,null,null,null,null),
('central','國立草屯商工職業學校（商業經營科）〔南投〕',18,31,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','國立草屯商工職業學校（資料處理科）〔南投〕',18,31,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','國立南投高級商業職業學校（應用英語科）',18,31,'職業類科','public','外語群',null,null,null,null,null),
('central','私立葳格高級中學（餐飲管理科）',18,31,'職業類科','private','餐旅群',null,null,null,null,null),
('central','臺中市立大甲高級工業職業學校（機械科）',18,31,'職業類科','public','動力機械群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（表演藝術科）',18,null,'職業類科','private','藝術群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（商業經營科）',18,34,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（國際貿易科）',18,34,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（應用日語科）',18,34,'職業類科','private','外語群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（應用英語科）',18,34,'職業類科','private','外語群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（觀光事業科）',18,34,'職業類科','private','餐旅群',null,null,null,null,null),
('central','私立僑泰高級中學（美容科）',18,31,'職業類科','private','家政群',null,null,null,null,null),
('central','私立僑泰高級中學（電子科）',18,31,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','私立僑泰高級中學（機械科）',18,31,'職業類科','private','機械群',null,null,null,null,null),
('central','私立僑泰高級中學（應用日語科）',18,31,'職業類科','private','外語群',null,null,null,null,null),
('central','私立青年高級中學（汽車科）',18,31,'職業類科','private','動力機械群',null,null,null,null,null),
('central','私立青年高級中學（餐飲管理科）',18,31,'職業類科','private','餐旅群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（電機科）',18,31,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','私立大明高級中學（汽車科）',18,30,'職業類科','private','動力機械群',null,null,null,null,null),
('central','私立明德高級中學（餐飲管理科）',16,40,'職業類科','private','餐旅群',null,null,null,null,null),
('central','私立青年高級中學（電子科）',16,37,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','私立明德高級中學（觀光事業科）',16,29,'職業類科','private','餐旅群',null,null,null,null,null),
('central','國立水里高級商工職業學校（普通科）〔南投〕',16,28,'普通科','public','學術群',null,null,null,null,null),
('central','私立僑泰高級中學（普通科）',16,28,'普通科','private','學術群',null,null,null,null,null),
('central','國立暨南國際大學附屬高級中學（綜合高中）〔南投〕',16,28,'普通科','public','學術群',null,null,null,null,null),
('central','國立草屯商工職業學校（會計事務科）〔南投〕',16,28,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','國立東勢高級工業職業學校（化工科）',16,28,'職業類科','public','化工群',null,null,null,null,null),
('central','南投縣立竹山高級中學（國際貿易科）',16,28,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','私立光華高級工業職業學校（資訊科）',16,28,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','私立明德高級中學（廣告設計科）',16,28,'職業類科','private','設計群',null,null,null,null,null),
('central','私立僑泰高級中學（觀光事業科）',16,28,'職業類科','private','餐旅群',null,null,null,null,null),
('central','私立青年高級中學（美容科）',16,28,'職業類科','private','家政群',null,null,null,null,null),
('central','私立青年高級中學（音樂科）',16,28,'職業類科','private','藝術群',null,null,null,null,null),
('central','南投縣立竹山高級中學（商業經營科）',16,28,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（資料處理科）',16,28,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（資訊科）',16,28,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（電子商務科）',16,28,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（電腦機械製圖科）',16,28,'職業類科','private','機械群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（廣告設計科）',16,28,'職業類科','private','設計群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（機械科）',16,28,'職業類科','private','機械群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（園藝科）',16,28,'職業類科','private','農業群',null,null,null,null,null),
('central','臺中市立新民高級中等學校（農場經營科）',16,28,'職業類科','private','農業群',null,null,null,null,null),
('central','國立臺中高級工業職業學校（機械科精密機械暨建教合作班）',16,28,'職業類科','public','機械群',null,null,null,null,null),
('central','南投縣立竹山高級中學（廣告設計科）',14,28,'職業類科','public','設計群',null,null,null,null,null),
('central','國立南投高級商業職業學校（商業經營科）',14,25,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','國立埔里高級工業職業學校（機械科）',14,25,'職業類科','public','機械群',null,null,null,null,null),
('central','私立明德高級中學（商業經營科）',14,25,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','私立同德家事商業職業學校（烘焙科）〔南投〕',12,42,'職業類科','private','餐旅群',null,null,null,null,null),
('central','私立明台高級中學（美容科）',12,31,'職業類科','private','家政群',null,null,null,null,null),
('central','私立光華高級工業職業學校（室內空間設計科）',12,28,'職業類科','private','設計群',null,null,null,null,null),
('central','私立光華高級工業職業學校（電子科）',12,22,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','南投縣立竹山高級中學（多媒體設計科）',12,22,'職業類科','public','設計群',null,null,null,null,null),
('central','南投縣立竹山高級中學（資料處理科）',12,22,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','私立明台高級中學（資料處理科）',11,28,'職業類科','private','商業與管理群',null,null,null,null,null),
('central','私立光華高級工業職業學校（機械科）',10,25,'職業類科','private','電機與電子群',null,null,null,null,null),
('central','國立南投高級商業職業學校（資料處理科）',10,19,'職業類科','public','商業與管理群',null,null,null,null,null),
('central','私立大明高級中學（觀光事業科）',10,19,'職業類科','private','餐旅群',null,null,null,null,null),
('central','私立僑泰高級中學（幼兒保育科）',10,18,'職業類科','private','家政群',null,null,null,null,null),
('central','私立僑泰高級中學（汽車科）',9,31,'職業類科','private','動力機械群',null,null,null,null,null),
('central','私立明台高級中學（室內設計科）',6,28,'職業類科','private','設計群',null,null,null,null,null),
('central','私立明台高級中學（餐飲管理科）',6,28,'職業類科','private','餐旅群',null,null,null,null,null),
('changhua','國立彰化女子高級中學 (普通科)',32,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (電機科)',29,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立彰化高級中學 (普通科)',29,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','國立彰化高級商業職業學校 (綜合高中)',29,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','國立員林高級中學 (普通科)',28,null,'普通科','public','學術群',null,null,null,null,null);
insert into public.schools (region,name,points,credits,type,ownership,vocational_group,min_chinese,min_english,min_math,min_science,min_social) values
('changhua','國立彰化師範大學附屬高級工業職業學校 (資訊科)',27,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (電子科)',27,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (控制科)',27,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (建築科)',25,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('changhua','國立彰化高級商業職業學校 (國際貿易科)',25,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立彰化高級商業職業學校 (廣告設計科)',25,null,'職業類科','public','設計群',null,null,null,null,null),
('changhua','彰化縣私立精誠高級中學 (普通科)',25,null,'普通科','private','學術群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (機電科)',25,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立彰化高級商業職業學校 (應用外語科)',24,null,'職業類科','public','外語群',null,null,null,null,null),
('changhua','國立彰化高級商業職業學校 (商業經營科)',24,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立溪湖高級中學 (綜合高中)',24,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','彰化縣立和美高級中學 (普通科)',24,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (機械科)',24,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (製圖科)',24,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立彰化高級商業職業學校 (資料處理科)',23,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立員林高級家事商業職業學校 (商業經營科)',23,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立秀水高級工業職業學校 (室內空間設計科)',23,null,'職業類科','public','設計群',null,null,null,null,null),
('changhua','國立員林崇實高級工業職業學校 (電機科)',23,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立員林高級家事商業職業學校 (家政科)',22,null,'職業類科','public','家政群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (汽車科)',22,null,'職業類科','public','動力機械群',null,null,null,null,null),
('changhua','國立員林崇實高級工業職業學校 (室內空間設計科)',22,null,'職業類科','public','設計群',null,null,null,null,null),
('changhua','國立員林崇實高級工業職業學校 (資訊科)',22,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (機械木模科)',22,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立秀水高級工業職業學校 (建築科)',21,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('changhua','國立員林高級家事商業職業學校 (應用外語科)',21,null,'職業類科','public','外語群',null,null,null,null,null),
('changhua','國立員林高級家事商業職業學校 (幼兒保育科)',21,null,'職業類科','public','家政群',null,null,null,null,null),
('changhua','國立員林高級家事商業職業學校 (國際貿易科)',21,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立秀水高級工業職業學校 (電機科)',21,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立彰化師範大學附屬高級工業職業學校 (鑄造科)',21,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立北斗高級家事商業職業學校 (餐飲管理科)',21,null,'職業類科','public','餐旅群',null,null,null,null,null),
('changhua','國立員林高級家事商業職業學校 (服裝科)',20,null,'職業類科','public','家政群',null,null,null,null,null),
('changhua','國立鹿港高級中學 (汽車科)',20,null,'職業類科','public','動力機械群',null,null,null,null,null),
('changhua','國立北斗高級家事商業職業學校 (國際貿易科)',20,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立北斗高級家事商業職業學校 (商業經營科)',20,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立北斗高級家事商業職業學校 (資料處理科)',20,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立員林崇實高級工業職業學校 (家具木工科)',20,null,'職業類科','public','設計群',null,null,null,null,null),
('changhua','國立北斗高級家事商業職業學校 (廣告設計科)',20,null,'職業類科','public','設計群',null,null,null,null,null),
('changhua','國立員林高級農工職業學校 (畜產保健科)',20,null,'職業類科','public','農業群',null,null,null,null,null),
('changhua','國立員林崇實高級工業職業學校 (冷凍空調科)',20,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','彰化縣立彰化藝術高級中學 (普通科)',20,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','國立和美實驗學校 (普通科)',20,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','彰化縣立成功高級中學 (普通科)',20,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','國立秀水高級工業職業學校 (製圖科)',20,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立秀水高級工業職業學校 (機械科)',20,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立永靖高級工業職業學校 (資訊科)',20,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立員林崇實高級工業職業學校 (化工科)',19,null,'職業類科','public','化工群',null,null,null,null,null),
('changhua','國立鹿港高級中學 (水產養殖科)',19,null,'職業類科','public','水產群',null,null,null,null,null),
('changhua','國立員林高級農工職業學校 (食品加工科)',19,null,'職業類科','public','食品群',null,null,null,null,null),
('changhua','國立北斗高級家事商業職業學校 (美容科)',19,null,'職業類科','public','家政群',null,null,null,null,null),
('changhua','國立鹿港高級中學 (商業經營科)',19,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立員林高級農工職業學校 (電子商務科)',19,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立永靖高級工業職業學校 (室內空間設計科)',19,null,'職業類科','public','設計群',null,null,null,null,null),
('changhua','國立員林高級農工職業學校 (園藝科)',19,null,'職業類科','public','農業群',null,null,null,null,null),
('changhua','國立鹿港高級中學 (普通科)',19,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','國立永靖高級工業職業學校 (建築科)',18,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('changhua','國立員林高級農工職業學校 (建築科)',18,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('changhua','國立員林高級農工職業學校 (農場經營科)',18,null,'職業類科','public','農業群',null,null,null,null,null),
('changhua','國立二林高級工商職業學校 (電機科)',18,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立員林高級農工職業學校 (機械科)',18,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立永靖高級工業職業學校 (機械科)',18,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立永靖高級工業職業學校 (製圖科)',18,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立二林高級工商職業學校 (室內空間設計科)',18,null,'職業類科','public','設計群',null,null,null,null,null),
('changhua','國立二林高級工商職業學校 (資料處理科)',18,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','國立二林高級工商職業學校 (電子科)',18,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('changhua','國立二林高級工商職業學校 (機械科)',18,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','國立二林高級工商職業學校 (建築科)',17,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('changhua','國立永靖高級工業職業學校 (化工科)',17,null,'職業類科','public','化工群',null,null,null,null,null),
('changhua','國立鹿港高級中學 (國際貿易科)',17,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','彰化縣立田中高級中學 (普通科)',17,null,'普通科','public','學術群',null,null,null,null,null),
('changhua','國立員林高級農工職業學校 (機電科)',17,null,'職業類科','public','機械群',null,null,null,null,null),
('changhua','彰化縣私立文興高級中學 (綜合高中)',16,null,'普通科','private','學術群',null,null,null,null,null),
('changhua','彰化縣私立正德高級中學 (應用外語科英文組)',15,null,'職業類科','private','外語群',null,null,null,null,null),
('changhua','國立二林高級工商職業學校 (商業經營科)',15,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('changhua','彰化縣私立正德高級中學 (普通科)',15,null,'普通科','private','學術群',null,null,null,null,null),
('changhua','彰化縣私立達德高級商工職業學校 (餐飲管理科)',15,null,'職業類科','private','餐旅群',null,null,null,null,null),
('changhua','彰化縣立二林高級中學 (普通科)',15,null,'普通科','public','普通科',null,null,null,null,null),
('taipei','北市建國高中(普通科(男))',33.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市第一女中(普通科(女))',33.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立薇閣高中(普通科)',33.6,null,'普通科','private','普通高中',null,null,null,null,null),
('taipei','國立師大附中(普通科(男))',32.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','國立師大附中(普通科(女))',32.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市成功高中(普通科(男))',31.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市中山女中(普通科(女))',30.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市松山高中(普通科(男))',30.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市松山高中(普通科(女))',29.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市大同高中(普通科)',29.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市中崙高中(普通科)',28.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','國立政大附中(普通科)',28.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北板橋高中(普通科(男))',28.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立延平高中(普通科)',28.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','新北板橋高中(普通科(女))',27.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市成淵高中(普通科)',27.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市大安高工(電機科)',27.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市麗山高中(普通科)',26.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立再興高中(普通科)',26.8,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','北市大直高中(普通科)',26.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北海山高中(普通科)',26.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市和平高中(普通科)',25.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市大安高工(電子科)',25.8,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市明倫高中(普通科)',25.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市內湖高中(普通科(男))',25.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立康橋高中(普通科)',25.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','北市大安高工(資訊科)',25.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市西松高中(普通科)',24.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北北大高中(普通科)',24.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市大安高工(控制科)',24.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市內湖高中(普通科(女))',23.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立南山高中(普通科)',23.8,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','北市百齡高中(普通科)',23.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市中正高中(普通科)',22.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市景美女中(普通科(女))',22.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北中和高中(普通科)',21.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市陽明高中(普通科)',21.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立復興實中(普通科)',21.8,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','私立育賢高中(普通科)',21.8,null,'普通科','private','普通高中',null,null,null,null,null),
('taipei','北市南湖高中(普通科)',21.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市大安高工(機械科)',21.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北永平高中(普通科)',20.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北新莊高中(普通科)',20.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市南港高中(普通科)',20.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市大安高工(冷凍空調科)',20.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市大安高工(建築科)',20.6,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('taipei','私立華興高中(普通科)',20.5,null,'普通科','private','普通高中',null,null,null,null,null),
('taipei','新北新北高中(普通科)',19.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北丹鳳高中(普通科)',19.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市華江高中(普通科)',19.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立東山高中(普通科)',19.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','北市大安高工(綜合高中)',19.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','國立華僑高中(普通科)',19.3,null,'普通科','public','普通高中',null,null,null,null,null),
('taipei','北市大安高工(圖文傳播科)',18.8,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','北市永春高中(普通科)',18.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','國立華僑高中(綜合高中)',18.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市大安高工(汽車科)',18.6,null,'職業類科','public','動力機械群',null,null,null,null,null),
('taipei','北市大安高工(電腦機械製圖科)',18.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','北市松山工農(電子科)',18.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市松山工農(電機科)',18.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','私立辭修高中(普通科)',17.8,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','新北新店高中(普通科)',17.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北錦和高中(普通科)',17.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北三民高中(普通科)',17.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','國立海大附中(海洋科技人才培育實驗班)',17.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市萬芳高中(普通科)',16.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市大理高中(綜合高中)',16.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北光復高中(綜合高中)',16.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市士林高商(廣告設計科)',16.6,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','北市松山工農(資訊科)',16.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市松山工農(機械科)',16.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北竹圍高中(普通科)',16.6,null,'普通科','public','普通高中',null,null,null,null,null),
('taipei','新北三重高中(普通科)',15.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市育成高中(普通科)',15.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立衛理女中(普通科(女))',15.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','北市中正高中(IB-CP班)',15.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市士林高商(會計事務科)',15.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','北市士林高商(應用英語科)',15.6,null,'職業類科','public','外語群',null,null,null,null,null),
('taipei','北市松山家商(國際貿易科)',15.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','新北新北高工(資訊科)',15.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市育成高中(國際文憑IBDP實驗專班)',15.6,null,'職業類科','public','特殊實驗班',null,null,null,null,null),
('taipei','新北林口高中(普通科)',15.4,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','基隆安樂高中(普通科)',15,null,'普通科','public','普通高中',null,null,null,null,null),
('taipei','北市松山工農(化工科)',14.8,null,'職業類科','public','化工群',null,null,null,null,null),
('taipei','北市松山家商(室內設計科)',14.8,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','北市士林高商(資料處理科)',14.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','北市松山工農(綜合高中)',14.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北鶯歌工商(應用日語科)',14.6,null,'職業類科','public','外語群',null,null,null,null,null),
('taipei','新北新北高工(電機科)',14.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北新北高工(電子科)',13.9,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北清水高中(普通科)',13.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市士林高商(商業經營科)',13.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','北市松山工農(汽車科)',13.6,null,'職業類科','public','動力機械群',null,null,null,null,null),
('taipei','北市松山工農(食品加工科)',13.6,null,'職業類科','public','食品群',null,null,null,null,null),
('taipei','北市松山家商(廣告設計科)',13.6,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','北市松山家商(應用英語科)',13.6,null,'職業類科','public','外語群',null,null,null,null,null),
('taipei','北市南港高工(電腦機械製圖科)',13.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','私立稻江護家(時尚造型科)',13.6,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','新北泰山高中(電子科)',13.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北新北高工(機械科)',13.4,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北樹林高中(普通科)',12.8,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北安康高中(普通科)',12.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北泰山高中(普通科)',12.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立靜修高中(普通科(女))',12.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','私立強恕高中(普通科)',12.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','北市士林高商(國際貿易科)',12.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','北市松山家商(會計事務科)',12.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','北市南港高工(電子科)',12.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市木柵高工(多媒體設計科)',12.6,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','新北新北高工(資料處理科)',12.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','新北新北高工進修部(資訊科(夜間班))',12.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','私立泰北高中(表演藝術科)',12.6,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','國立基隆商工(商業經營科)',12.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','私立育達高中(觀光事業科)',12.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','北市南港高工(建築科)',12.4,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('taipei','新北三重商工(應用英語科)',12.4,null,'職業類科','public','外語群',null,null,null,null,null),
('taipei','新北淡水商工(園藝科)',12.4,null,'職業類科','public','農業群',null,null,null,null,null),
('taipei','新北瑞芳高工(建築科)',12.4,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('taipei','北市復興高中(普通科)',11.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市內湖高工(資訊科)',11.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市內湖高工(電機科)',11.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市松山工農(園藝科)',11.6,null,'職業類科','public','農業群',null,null,null,null,null),
('taipei','北市松山家商(資料處理科)',11.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','新北新北高工(汽車科)',11.6,null,'職業類科','public','動力機械群',null,null,null,null,null);
insert into public.schools (region,name,points,credits,type,ownership,vocational_group,min_chinese,min_english,min_math,min_science,min_social) values
('taipei','新北新北高工(製圖科)',11.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北新北高工(應用英語科)',11.6,null,'職業類科','public','外語群',null,null,null,null,null),
('taipei','新北新北高工(鑄造科)',11.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北淡水商工(餐飲管理科)',11.6,null,'職業類科','public','餐旅群',null,null,null,null,null),
('taipei','新北鶯歌工商(資訊科)',11.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','國立海大附中(航海科)',11.6,null,'職業類科','public','海事群',null,null,null,null,null),
('taipei','國立海大附中(輪機科)',11.6,null,'職業類科','public','海事群',null,null,null,null,null),
('taipei','私立幼華高中(普通科)',11.6,null,'普通科','private','普通高中',null,null,null,null,null),
('taipei','新北淡水商工(會計事務科)',11.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','私立莊敬工家(電影電視科)',11.6,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','私立莊敬工家(音樂科)',11.6,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','私立金甌女中(多媒體設計科(女))',11.4,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立淡江高中(室內空間設計科)',11.4,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','北市內湖高工(控制科)',11.1,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北三重商工(資料處理科)',10.8,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','新北鶯歌工商(廣告設計科)',10.8,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','私立東海高中(多媒體動畫科)',10.8,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','私立能仁家商(多媒體設計科)',10.8,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','新北秀峰高中(普通科)',10.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立崇光女中(普通科(女))',10.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','私立光仁高中(普通科)',10.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','北市大安高工進修部(電子科(夜間班))',10.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市松山家商(商業經營科)',10.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','北市南港高工(土木科)',10.6,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('taipei','北市南港高工(汽車科)',10.6,null,'職業類科','public','動力機械群',null,null,null,null,null),
('taipei','北市南港高工(機械科)',10.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北新北高工(模具科)',10.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北三重商工(機械科)',10.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','私立靜修高中(應用英語科(女))',10.6,null,'職業類科','private','外語群',null,null,null,null,null),
('taipei','私立智光商工(資料處理科)',10.6,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('taipei','私立樹人家商(觀光事業科)',10.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','國立海大附中(烘焙科)',10.6,null,'職業類科','public','食品群',null,null,null,null,null),
('taipei','新北淡水商工(商業經營科)',10.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','私立喬治工商(餐飲管理科)',10.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','北市南港高工(冷凍空調科)',10.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北新北高工進修部(資料處理科(夜間班))',10.4,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','私立稻江護家(應用英語科)',10.4,null,'職業類科','private','外語群',null,null,null,null,null),
('taipei','私立智光商工(資訊科)',10.4,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('taipei','私立淡江高中(綜合高中)',10.4,null,'普通科','private','綜合高中',null,null,null,null,null),
('taipei','國立基隆商工(綜合高中)',10.4,null,'普通科','public','綜合高中',null,null,null,null,null),
('taipei','私立新民高中(普通科)',10.1,null,'普通科','private','普通高中',null,null,null,null,null),
('taipei','私立稻江高商(應用日語科)',10.1,null,'職業類科','private','外語群',null,null,null,null,null),
('taipei','私立樹人家商(美容科)',10,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','私立及人高中(普通科)',10,null,'普通科','private','普通高中',null,null,null,null,null),
('taipei','新北明德高中(普通科)',9.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立金甌女中(普通科(女))',9.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','私立中信高中(普通科)',9.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','北市內湖高工(應用英語科)',9.6,null,'職業類科','public','外語群',null,null,null,null,null),
('taipei','北市南港高工(模具科)',9.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','北市木柵高工(電機科)',9.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北三重商工(汽車科)',9.6,null,'職業類科','public','動力機械群',null,null,null,null,null),
('taipei','新北瑞芳高工(室內空間設計科)',9.6,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','新北樟樹實中(多媒體動畫科)',9.6,null,'職業類科','public','藝術群',null,null,null,null,null),
('taipei','新北泰山高中(機械科)',9.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','私立能仁家商(流行服飾科)',9.6,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','私立莊敬工家(資訊科)',9.6,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('taipei','私立智光商工進修部(餐飲管理科(夜間班))',9.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','私立樹人家商(流通管理科)',9.6,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('taipei','私立崇義高中(電子商務科)',9.6,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('taipei','私立莊敬工家(流行服飾科)',9.6,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','北市南港高工(重機科)',9.5,null,'職業類科','public','動力機械群',null,null,null,null,null),
('taipei','北市南港高工(電機科)',9.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市木柵高工(冷凍空調科)',9.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北鶯歌工商(陶瓷工程科)',9.4,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','私立大同高中(普通科)',9.1,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','新北三重商工(控制科)',9.1,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北鶯歌工商(美術工藝科)',9,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','私立育達高中(表演藝術科)',9,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','北市南港高工(劇場藝術科)',8.9,null,'職業類科','public','藝術群',null,null,null,null,null),
('taipei','私立恆毅高中(普通科)',8.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','私立竹林高中(普通科)',8.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','新北雙溪高中(綜合高中)',8.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市內湖高工(冷凍空調科)',8.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市南港高工(鑄造科)',8.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','北市木柵高工(配管科)',8.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','北市木柵高工(電子科)',8.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','北市木柵高工(模具科)',8.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北三重商工(板金科)',8.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北三重商工(商業經營科)',8.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','新北淡水商工(資訊科)',8.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北淡水商工(電機科)',8.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','私立東方工商(時尚造型科)',8.6,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','私立東方工商(餐飲管理科)',8.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','私立金甌女中(商業經營科(女))',8.6,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('taipei','私立開南高中(餐飲管理科)',8.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','私立靜修高中(應用日語科(女))',8.6,null,'職業類科','private','外語群',null,null,null,null,null),
('taipei','私立東海高中(餐飲管理科)',8.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','私立豫章工商(資訊科)',8.6,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('taipei','私立醒吾高中(商業經營科)',8.6,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('taipei','新北鶯歌工商(陶瓷工程科(設計))',8.6,null,'職業類科','public','設計群',null,null,null,null,null),
('taipei','北市木柵高工(電機科(乙))',8.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','私立能仁家商(幼兒保育科)',8.6,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','私立樹人家商(影劇科)',8.6,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','北市內湖高工(電子科)',8.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','新北瑞芳高工(資訊科)',8.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','國立基隆商工(資訊科)',8.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','私立二信高中(外語群不分科)',8.4,null,'職業類科','private','外語群',null,null,null,null,null),
('taipei','國立基隆商工(資料處理科)',8.4,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','私立開南高中(資訊科)',8.4,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('taipei','北市大安高工進修部(汽車科(夜間班))',8,null,'職業類科','public','動力機械群',null,null,null,null,null),
('taipei','國立基隆高中(普通科(男))',7.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','私立育達高中(普通科)',7.6,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','北市木柵高工(製圖科)',7.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','北市木柵高工(鑄造科)',7.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北新北高工進修部(汽車科(夜間班))',7.6,null,'職業類科','public','動力機械群',null,null,null,null,null),
('taipei','新北瑞芳高工(電子科)',7.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','私立大同高中(資訊科)',7.6,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('taipei','私立金甌女中(應用日語科(女))',7.6,null,'職業類科','private','外語群',null,null,null,null,null),
('taipei','私立景文高中(商業經營科)',7.6,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('taipei','私立開南高中(廣告設計科)',7.6,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立稻江護家(餐飲管理科)',7.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','私立復興商工(美術科)',7.6,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','私立能仁家商(表演藝術科)',7.6,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','私立莊敬工家(餐飲管理科)',7.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','新北新北高工進修部(機械科(夜間班))',7.4,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','私立復興商工(美工科)',7.4,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立智光商工(電子科)',7.4,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('taipei','私立智光商工(多媒體設計科)',7.4,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立莊敬工家(資料處理科)',7.1,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('taipei','私立智光商工(觀光事業科)',7.1,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','私立大同高中(資料處理科)',7.1,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('taipei','私立能仁家商(廣告設計科)',7,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立莊敬工家(幼兒保育科)',6.9,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','新北淡水商工(普通科)',6.6,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','北市木柵高工(機械科)',6.6,null,'職業類科','public','機械群',null,null,null,null,null),
('taipei','新北鶯歌工商(資料處理科)',6.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('taipei','私立稻江護家(廣告設計科)',6.6,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立復興商工(資料處理科)',6.6,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('taipei','私立復興商工(廣告設計科)',6.6,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立莊敬工家(表演藝術科)',6.6,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','私立稻江高商(廣告設計科)',6.6,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立稻江高商(資訊科)',6.6,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('taipei','私立育達高中(多媒體設計科)',6.6,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立金陵女中(普通科(女))',6.4,null,'普通科','private','學術群',null,null,null,null,null),
('taipei','國立台灣戲曲學院(高職部)(劇場藝術科)',6.4,null,'職業類科','public','藝術群',null,null,null,null,null),
('taipei','國立海大附中(漁業科)',6.4,null,'職業類科','public','水產群',null,null,null,null,null),
('taipei','私立能仁家商(餐飲管理科)',6.4,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','私立莊敬工家(多媒體動畫科)',6.4,null,'職業類科','private','藝術群',null,null,null,null,null),
('taipei','私立育達高中(餐飲管理科)',6.4,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','私立開南高中(電機科)',5.6,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('taipei','私立莊敬工家(美容科)',5.6,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','私立智光商工(餐飲管理科)',5.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','新北石碇高中(綜合高中)',5.4,null,'普通科','public','學術群',null,null,null,null,null),
('taipei','新北淡水商工(電子科)',5.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('taipei','私立能仁家商(美容科)',5.4,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','私立樹人家商(餐飲管理科)',5.4,null,'職業類科','private','餐旅群',null,null,null,null,null),
('taipei','私立景文高中(汽車科)',5.2,null,'職業類科','private','動力機械群',null,null,null,null,null),
('taipei','私立稻江護家(幼兒保育科)',5.2,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','私立復興商工(室內設計科)',5.2,null,'職業類科','private','設計群',null,null,null,null,null),
('taipei','私立泰北高中(時尚造型科)',5.1,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','私立喬治工商進修部(時尚造型科(兩日班))',5.1,null,'職業類科','private','家政群',null,null,null,null,null),
('taipei','私立豫章工商(餐飲管理科)',5.1,null,'職業類科','private','餐旅群',null,null,null,null,null),
('tainan','國立台南第一高級中學(普通科)',28.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立台南女子高級中學(普通科)',26.8,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立台南科學工業園區實驗高級中學(普通科)',26.8,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立家齊高級中等學校(男)(普通科)',26.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立家齊高級中等學校(女)(普通科)',24.8,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立台南第二高級中學(普通科)',23.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立臺南家齊高中（流行服飾科）',22.4,null,'職業類科','public','家政群',null,null,null,null,null),
('tainan','台南市立新營高級中學(普通科)',21.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立成功大學附屬高級中學(普通科)',21.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(飛機修護科）',21.4,null,'職業類科','public','動力機械群',null,null,null,null,null),
('tainan','台南市立大灣高級中學(普通科)',20.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','台南市私立德光高級中學(普通科)',20.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','臺南市立沙崙國際高級中等學校(普通科)',20.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立台南高商(應用外語科）',20.4,null,'職業類科','public','外語群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(電機科）',19.8,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立新營高級中學(應用英語科)',19.4,null,'職業類科','public','外語群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(資訊科）',18.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(汽車科）',18.4,null,'職業類科','public','動力機械群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(建築科）',18.4,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('tainan','國立新化高級工業職業學校(資料處理科)',18.4,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('tainan','國立新營高級中學(商業經營科)',18.4,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('tainan','國立新營高級中學(資料處理科)',18.4,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('tainan','國立新營高級中學(電子商務科)',18.4,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('tainan','台南市私立永仁高級中學(普通科)',17.8,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','台南市私立港明高級中學(普通科)',17.8,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','台南市立南寧高級中學(普通科)',17.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(電子科）',17.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立台南高商(應用英語科）',17.6,null,'職業類科','public','外語群',null,null,null,null,null),
('tainan','國立臺南家齊高中（餐飲管理科）',17.4,null,'職業類科','public','餐旅群',null,null,null,null,null),
('tainan','國立新化高級工業職業學校（機械科）',17.4,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','國立新化高級工業職業學校（電機科）',17.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立成功大學附屬高級中學（綜合科）',16.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立台南高商(廣告設計科）',16.6,null,'職業類科','public','設計群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(化工科）',15.6,null,'職業類科','public','化工群',null,null,null,null,null),
('tainan','台南市立新化高級中學(普通科)',15.4,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(機械科）',15.4,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','台南市立土城高級中學(普通科)',14.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','國立台南高商(觀光事業科）',14.6,null,'職業類科','public','餐旅群',null,null,null,null,null),
('tainan','國立台南高商(國際貿易科）',14.6,null,'職業類科','public','商業管理群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(製圖科）',14.4,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','台南市私立聖功女中(普通科)',13.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','國立台南高商(會計事務科）',13.6,null,'職業類科','public','商業管理群',null,null,null,null,null),
('tainan','臺南市黎明高級中學(普通科)',13.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','國立新化高級工業職業學校(資訊科)',13.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立新化高級工業職業學校(電子科)',13.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立新化高級工業職業學校(化工科)',13.6,null,'職業類科','public','化工群',null,null,null,null,null),
('tainan','國立新化高級工業職業學校(製圖科)',13.6,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','國立台南高商(商業經營科）',13.6,null,'職業類科','public','商業管理群',null,null,null,null,null);
insert into public.schools (region,name,points,credits,type,ownership,vocational_group,min_chinese,min_english,min_math,min_science,min_social) values
('tainan','國立成功大學附屬臺南工業高級中等學校(土木科）',13.4,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('tainan','台南市立新豐高級中學(普通科)',12.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','台南市立北門高級中學(普通科)',12.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','台南市私立光華高級中學(普通科)',12.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','台南市私立慈濟高級中學(普通科)',12.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','國立台南高商(資料處理科）',12.6,null,'職業類科','public','商業管理群',null,null,null,null,null),
('tainan','國立新化高級工業職業學校(建築科)',12.6,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(板金科）',12.4,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校(鑄造科）',12.4,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','台南市立善化高級中學(普通科)',11.8,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','台南市私立長榮高級中學(普通科)',11.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','台南市私立光華高級中學（綜合科）',11.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','台南市私立六合高級中學(普通科)',10.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','台南市立新豐高級中學(綜合科)',9.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','台南市立曾文農工高級中等學校(普通科)',9.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','台南市立後壁高級中學(普通科)',9.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','台南市立玉井高級中學(普通科)',9.6,null,'普通科','public','學術群',null,null,null,null,null),
('tainan','臺南市光華高級中學(商業經營科)',9.6,null,'職業類科','private','商業與管理群',null,null,null,null,null),
('tainan','國立白河高級商工職業學校(機械科)',9.6,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','國立白河高級商工職業學校(資訊科)',9.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立白河高級商工職業學校(電機科)',9.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','臺南市光華高級中學(餐飲管理科)',8.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('tainan','臺南市光華高級中學(多媒體設計科)',8.6,null,'職業類科','private','設計群',null,null,null,null,null),
('tainan','臺南市光華高級中學(幼兒保育科)',8.6,null,'職業類科','private','家政群',null,null,null,null,null),
('tainan','臺南市光華高級中學(流行服飾科)',8.6,null,'職業類科','private','家政群',null,null,null,null,null),
('tainan','國立白河高級商工職業學校(汽車科)',8.6,null,'職業類科','public','動力機械群',null,null,null,null,null),
('tainan','國立白河高級商工職業學校(土木科)',8.6,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('tainan','國立白河高級商工職業學校(商業經營科)',8.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('tainan','國立白河高級商工職業學校(資料處理科)',8.6,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('tainan','國立臺南高級海事水產職業學校(電子科）',8.6,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立臺南高級海事水產職業學校(水產食品科）',8.6,null,'職業類科','public','食品群',null,null,null,null,null),
('tainan','國立後壁高級中學(資訊科)',8.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立後壁高級中學(電機科)',8.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立臺南高級海事水產職業學校(機電科）',8.4,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','國立臺南高級海事水產職業學校(商業經營科）',8.4,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('tainan','國立臺南高級海事水產職業學校(輪機科）',8.2,null,'職業類科','public','海事群',null,null,null,null,null),
('tainan','國立臺南高級海事水產職業學校(電子商務科）',7.8,null,'職業類科','public','商業與管理群',null,null,null,null,null),
('tainan','臺南市私立瀛海高級中學(普通科)',7.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','臺南市崑山高級中等學校(普通科)',7.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','臺南市私立南光高級中學(普通科)',7.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','臺南市私立中信國際高級中等學校(普通科)',7.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','臺南市私立明達高級中學(普通科)',7.6,null,'普通科','private','學術群',null,null,null,null,null),
('tainan','國立後壁高級中學(建築科)',7.4,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('tainan','國立後壁高級中學(美工科)',7.4,null,'職業類科','public','設計群',null,null,null,null,null),
('tainan','國立後壁高級中學(室內空間設計科)',7.4,null,'職業類科','public','設計群',null,null,null,null,null),
('tainan','國立後壁高級中學(廣告設計科)',7.4,null,'職業類科','public','設計群',null,null,null,null,null),
('tainan','國立後壁高級中學(多媒體設計科)',7.4,null,'職業類科','public','設計群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校進修部(機械科)',7.4,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校進修部(資訊科)',7.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校進修部(電子科)',7.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校進修部(電機科)',7.4,null,'職業類科','public','電機與電子群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校進修部(建築科)',7.4,null,'職業類科','public','土木與建築群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校進修部(機電科)',7.4,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校進修部(室內空間設計科)',7.4,null,'職業類科','public','設計群',null,null,null,null,null),
('tainan','國立成功大學附屬臺南工業高級中等學校進修部(電腦機械製圖科)',7.4,null,'職業類科','public','機械群',null,null,null,null,null),
('tainan','國立臺南高級海事水產職業學校(水產養殖科）',7.4,null,'職業類科','public','水產群',null,null,null,null,null),
('tainan','臺南市私立南英高級商工職業學校(汽車科)',6.6,null,'職業類科','private','動力機械群',null,null,null,null,null),
('tainan','臺南市私立南英高級商工職業學校(電機空調科)',6.6,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('tainan','臺南市私立南英高級商工職業學校(餐飲管理科)',6.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('tainan','臺南市私立南英高級商工職業學校(應用日語科)',6.6,null,'職業類科','private','外語群',null,null,null,null,null),
('tainan','臺南市私立南英高級商工職業學校(電影電視科)',6.6,null,'職業類科','private','藝術群',null,null,null,null,null),
('tainan','臺南市私立南英高級商工職業學校(多媒體動畫科)',6.6,null,'職業類科','private','藝術群',null,null,null,null,null),
('tainan','臺南市亞洲高級餐旅職業學校(餐飲管理科)',6.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('tainan','臺南市私立慈幼高級工商職業學校(汽車科)',6.6,null,'職業類科','private','動力機械群',null,null,null,null,null),
('tainan','臺南市私立慈幼高級工商職業學校(資訊科)',6.6,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('tainan','臺南市私立慈幼高級工商職業學校(電機科)',6.6,null,'職業類科','private','電機與電子群',null,null,null,null,null),
('tainan','臺南市私立慈幼高級工商職業學校(烘焙科)',6.6,null,'職業類科','private','食品群',null,null,null,null,null),
('tainan','臺南市陽明高級工商職業學校(家具木工科)',6.6,null,'職業類科','private','設計群',null,null,null,null,null),
('tainan','臺南市私立育德工業家事職業學校(汽車科)',6.6,null,'職業類科','private','動力機械群',null,null,null,null,null),
('tainan','臺南市私立育德工業家事職業學校(餐飲管理科)',6.6,null,'職業類科','private','餐旅群',null,null,null,null,null),
('tainan','臺南市私立育德工業家事職業學校(時尚造型科)',6.6,null,'職業類科','private','家政群',null,null,null,null,null),
('hsinchu','國立新竹科學園區實驗高級中等學校（普通科）',30,35,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','國立新竹高級中學（普通科）',30,31,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','國立新竹女子高級中學（普通科）',30,29,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','國立竹北高級中學（普通科）',28,29,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','國立竹北高級中學（資訊科）',28,27,'職業類科','public','電機與電子群',null,null,null,null,null),
('hsinchu','新竹市立建功高級中學（普通科）',28,26,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','新竹縣立六家高級中學（普通科）',26,25,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','國立新竹高級工業職業學校（電機科）',26,24,'職業類科','public','電機與電子群',null,null,null,null,null),
('hsinchu','國立新竹高級商業職業學校（綜合高中）',26,24,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','私立義民高級中學（普通科）',26,23,'普通科','private','學術群',null,null,null,null,null),
('hsinchu','國立竹北高級中學（商業經營科）',26,22,'職業類科','public','商業與管理群',null,null,null,null,null),
('hsinchu','國立新竹高級工業職業學校（資訊科）',26,22,'職業類科','public','電機與電子群',null,null,null,null,null),
('hsinchu','國立新竹高級工業職業學校（化工科）',24,22,'職業類科','public','化工群',null,null,null,null,null),
('hsinchu','私立曙光女子高級中學（普通科）',24,21,'普通科','private','學術群',null,null,null,null,null),
('hsinchu','國立新竹高級工業職業學校（室內設計科）',24,18,'職業類科','public','設計群',null,null,null,null,null),
('hsinchu','國立新竹高級工業職業學校（製圖科）',22,21,'職業類科','public','機械群',null,null,null,null,null),
('hsinchu','國立新竹高級商業職業學校（應用英文科）',22,20,'職業類科','public','外語群',null,null,null,null,null),
('hsinchu','國立新竹高級工業職業學校（板金科）',22,19,'職業類科','public','機械群',null,null,null,null,null),
('hsinchu','新竹市立成德高級中學（普通科）',22,18,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','國立竹東高級中學（普通科）',22,18,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','國立竹南高級中學（普通科）',22,17,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','國立新竹高級商業職業學校（商業經營科）',22,16,'職業類科','public','商業與管理群',null,null,null,null,null),
('hsinchu','國立新竹高級商業職業學校（資料處理科）',22,15,'職業類科','public','商業與管理群',null,null,null,null,null),
('hsinchu','新竹縣湖口高級中學（普通科）',20,18,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','新竹市香山高級中學（普通科）',20,18,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','國立新竹高級商業職業學校（國際貿易科）',20,17,'職業類科','public','商業與管理群',null,null,null,null,null),
('hsinchu','私立曙光女子高級中學（商業經營科）',20,16,'職業類科','private','商業與管理群',null,null,null,null,null),
('hsinchu','國立關西高級中學（綜合高中）',20,16,'職業類科','public','學術群',null,null,null,null,null),
('hsinchu','新竹縣湖口高級中學（商業經營科）',20,15,'職業類科','public','商業與管理群',null,null,null,null,null),
('hsinchu','國立竹南高級中學（化工科）',20,15,'職業類科','public','化工群',null,null,null,null,null),
('hsinchu','私立曙光女子高級中學（應用英文科）',20,14,'職業類科','private','外語群',null,null,null,null,null),
('hsinchu','新竹市香山高級中學（資料處理科）',20,14,'職業類科','public','商業與管理群',null,null,null,null,null),
('hsinchu','新竹市香山高級中學（美術工藝科）',20,14,'職業類科','public','設計群',null,null,null,null,null),
('hsinchu','私立磐石高級中學（普通科）',20,13,'普通科','private','學術群',null,null,null,null,null),
('hsinchu','私立忠信高級中學（綜合高中科）',20,13,'普通科','private','學術群',null,null,null,null,null),
('hsinchu','私立義民高級中學（廣告設計科）',20,13,'職業類科','private','設計群',null,null,null,null,null),
('hsinchu','私立義民高級中學（資訊科）',20,12,'職業類科','private','電機與電子群',null,null,null,null,null),
('hsinchu','私立磐石高級中學（電機科）',20,12,'職業類科','private','電機與電子群',null,null,null,null,null),
('hsinchu','國立關西高級中學（畜牧科）',20,12,'職業類科','public','農業群',null,null,null,null,null),
('hsinchu','私立光復高級中學（普通科）',20,11,'職業類科','private','學術群',null,null,null,null,null),
('hsinchu','私立義民高級中學（資料處理科）',20,10,'職業類科','private','商業與管理群',null,null,null,null,null),
('hsinchu','私立曙光女子高級中學（應用日語科）',20,10,'職業類科','private','外語群',null,null,null,null,null),
('hsinchu','苗栗大同高級中學（普通科）',18,13,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','苗栗卓蘭高級中學（普通科）',18,13,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','苗栗興華高級中學（普通科）',18,11,'普通科','public','學術群',null,null,null,null,null),
('hsinchu','私立內思高級中學（電機科）',18,11,'職業類科','private','電機與電子群',null,null,null,null,null),
('hsinchu','私立義民高級中學（幼兒保育科）',18,11,'職業類科','private','家政群',null,null,null,null,null),
('hsinchu','苗栗農工（機械科）',18,9,'職業類科','public','機械群',null,null,null,null,null),
('hsinchu','苗栗興華高級中學（商業經營科）',16,8,'職業類科','public','商業與管理群',null,null,null,null,null),
('hsinchu','私立光復高級中學（多媒體設計科）',16,8,'職業類科','private','設計群',null,null,null,null,null),
('hsinchu','大湖農工（室內設計科）',16,8,'職業類科','public','設計群',null,null,null,null,null);
commit;
